# Service for integrating with ComfyUI API for stock photo extraction
# ComfyUI is a node-based Stable Diffusion UI that supports image editing
class ComfyUiService
  def self.base_url
    ENV["COMFY_UI_API_URL"] || "http://localhost:8188"
  end

  class << self
    # Extract stock photo from original image using ComfyUI + Qwen Image Edit
    # @param original_image_blob [ActiveStorage::Blob] The original image blob
    # @param extraction_prompt [String] The extraction prompt generated by ExtractionPromptBuilder
    # @return [Hash] Result containing extracted image data or error
    def extract_stock_photo(original_image_blob:, extraction_prompt:)
      Rails.logger.info "Starting ComfyUI stock photo extraction"

      # Validate inputs
      unless original_image_blob.present?
        raise ArgumentError, "Original image blob is required"
      end

      unless extraction_prompt.present?
        raise ArgumentError, "Extraction prompt is required"
      end

      # Check ComfyUI availability
      check_comfyui_availability!

      # Upload image to ComfyUI and get filename
      image_filename = upload_image(original_image_blob)

      # Build workflow payload using actual workflow template
      workflow_data = build_workflow(image_filename, extraction_prompt)

      # Generate client_id for WebSocket tracking (must match between submission and WebSocket)
      client_id = SecureRandom.uuid

      # Submit to ComfyUI with client_id for WebSocket tracking
      job_id = submit_workflow(workflow_data, client_id: client_id)

      # Try WebSocket first for real-time completion, fallback to polling
      begin
        result = wait_for_completion_via_websocket(job_id, client_id: client_id)
        Rails.logger.info "ComfyUI extraction completed via WebSocket (job: #{job_id})"
        result
      rescue StandardError => ws_error
        Rails.logger.warn "WebSocket completion failed: #{ws_error.message}. Falling back to polling..."
        # Fallback to polling
        result = poll_for_completion(job_id)
        Rails.logger.info "ComfyUI extraction completed via polling (job: #{job_id})"
        result
      end
    rescue ArgumentError => e
      # Re-raise ArgumentError - these are validation errors that callers should handle
      raise
    rescue StandardError => e
      Rails.logger.error "ComfyUI extraction failed: #{e.message}"
      Rails.logger.error e.backtrace.first(10).join("\n")
      { "error" => e.message, "success" => false }
    end

    # Handle WebSocket messages from ComfyUI
    # Public method so it can be called from WebSocket callback blocks
    def handle_websocket_message(message, job_id)
      return unless message.is_a?(Hash)

      case message["type"]
      when "executing"
        data = message["data"]
        if data && data["node"].nil? && data["prompt_id"] == job_id
          # Execution complete - fetch results
          Rails.logger.info "ComfyUI job completed via WebSocket (prompt_id: #{job_id})"
          result = fetch_job_results_after_completion(job_id)
          yield(result) if result && block_given?
        end
      when "progress"
        # Progress updates - log for debugging
        progress_data = message["data"]
        Rails.logger.debug "ComfyUI progress: #{progress_data.inspect}"
      when "execution_error"
        error_data = message["data"]
        error_msg = error_data["error_message"] || error_data["message"] || "Unknown error"
        Rails.logger.error "ComfyUI execution error: #{error_msg}"
        raise StandardError, "ComfyUI execution error: #{error_msg}"
      when "execution_start"
        # Job started executing
        Rails.logger.debug "ComfyUI job started executing"
      when "execution_cached"
      # Node output was cached
      Rails.logger.debug "ComfyUI node output cached"
      end
  end

  # Fetch job results after WebSocket completion notification
  # Public method so it can be called from WebSocket callback blocks
  def fetch_job_results_after_completion(job_id)
    base_uri = URI(base_url)
    http = Net::HTTP.new(base_uri.host, base_uri.port)
    http.open_timeout = 10
    http.read_timeout = 30

    # Get history
    request = Net::HTTP::Get.new("/history/#{job_id}")
    response = http.request(request)

    unless response.code == "200"
      raise StandardError, "Failed to fetch ComfyUI history: HTTP #{response.code}"
    end

    result = JSON.parse(response.body)
    job_data = result[job_id]

    unless job_data && job_data.is_a?(Hash)
      raise StandardError, "ComfyUI history does not contain job data for #{job_id}"
    end

    outputs = job_data["outputs"] || {}
    status = job_data["status"]

    # Check if job failed
    if status && status["status_str"] == "error"
      error_msg = if status["messages"] && status["messages"].any?
        status["messages"].join("; ")
      else
        "Unknown error"
      end
      raise StandardError, "ComfyUI job failed: #{error_msg}"
    end

    # Extract image data
    image_data = extract_image_from_outputs(outputs, http, base_uri)

    unless image_data
      raise StandardError, "ComfyUI did not return image data"
    end

    image_size = image_data.respond_to?(:bytesize) ? image_data.bytesize : image_data.size
    Rails.logger.info "ComfyUI returned image data: #{image_size} bytes (#{(image_size / 1024.0).round(2)} KB)"

    {
      "success" => true,
      "job_id" => job_id,
      "outputs" => outputs,
      "image_data" => image_data
    }
  rescue JSON::ParserError => e
    Rails.logger.error "Failed to parse ComfyUI history response: #{e.message}"
    raise StandardError, "Invalid JSON from ComfyUI history endpoint"
  end

  private

    def check_comfyui_availability!
      base_uri = URI(base_url)

      Rails.logger.info "Checking ComfyUI availability at #{base_url}..."

      begin
        http = Net::HTTP.new(base_uri.host, base_uri.port)
        http.open_timeout = 3
        http.read_timeout = 3

        # Check if ComfyUI is up (simple GET to root)
        response = http.get("/")
        unless response.code.to_i < 500
          raise StandardError, "ComfyUI API returned status #{response.code}"
        end

        Rails.logger.info "✓ ComfyUI is available at #{base_url}"
      rescue Errno::ECONNREFUSED, Errno::EHOSTUNREACH, SocketError => e
        Rails.logger.error "Cannot connect to ComfyUI at #{base_url}: #{e.message}"
        raise StandardError, "ComfyUI service is not available at #{base_url}. Please ensure ComfyUI is running."
      rescue Net::ReadTimeout, Net::OpenTimeout, Timeout::Error => e
        Rails.logger.error "Timeout connecting to ComfyUI: #{e.message}"
        raise StandardError, "Timeout connecting to ComfyUI service. Please check if ComfyUI is running."
      rescue StandardError => e
        raise e if e.message.include?("ComfyUI")
        Rails.logger.error "Error checking ComfyUI availability: #{e.message}"
        raise StandardError, "Failed to verify ComfyUI availability: #{e.message}"
      end
    end

    def upload_image(blob)
      # Upload image to ComfyUI and return filename
      base_uri = URI(base_url)
      http = Net::HTTP.new(base_uri.host, base_uri.port)
      http.open_timeout = 10
      http.read_timeout = 10

      image_data = blob.download
      # Force binary encoding to ensure image data is handled correctly
      image_data.force_encoding("BINARY") if image_data.respond_to?(:force_encoding)
      Rails.logger.info "Uploading image to ComfyUI: blob_id=#{blob.id}, size=#{image_data.bytesize} bytes, content_type=#{blob.content_type}"

      extension = blob.filename.extension.presence || "jpg"
      filename = "#{SecureRandom.hex(8)}.#{extension}"

      request = Net::HTTP::Post.new("/upload/image")
      form_data = [
        [ "image", image_data, { filename: filename, content_type: blob.content_type } ]
      ]
      request.set_form(form_data, "multipart/form-data")

      response = http.request(request)

      unless response.code == "200"
        raise StandardError, "ComfyUI image upload returned status #{response.code}: #{response.body}"
      end

      parsed = JSON.parse(response.body)
      uploaded_filename = parsed["name"] || filename

      Rails.logger.info "Image uploaded to ComfyUI: #{uploaded_filename}"
      uploaded_filename
    rescue JSON::ParserError => e
      Rails.logger.error "Failed to parse ComfyUI upload response: #{e.message}"
      raise StandardError, "Invalid response from ComfyUI upload API"
    end

    def build_workflow(image_filename, extraction_prompt)
      # Build ComfyUI workflow using the actual workflow template
      # This workflow uses Qwen Image Edit for stock photo extraction
      workflow = {
        "60" => {
          "inputs" => {
            "filename_prefix" => "ComfyUI",
            "images" => [
              "115:8",
              0
            ]
          },
          "class_type" => "SaveImage",
          "_meta" => {
            "title" => "Save Image"
          }
        },
        "78" => {
          "inputs" => {
            "image" => image_filename
          },
          "class_type" => "LoadImage",
          "_meta" => {
            "title" => "Load Image"
          }
        },
        "115:75" => {
          "inputs" => {
            "strength" => 1,
            "model" => [
              "115:66",
              0
            ]
          },
          "class_type" => "CFGNorm",
          "_meta" => {
            "title" => "CFGNorm"
          }
        },
        "115:39" => {
          "inputs" => {
            "vae_name" => "qwen_image_vae.safetensors"
          },
          "class_type" => "VAELoader",
          "_meta" => {
            "title" => "Load VAE"
          }
        },
        "115:38" => {
          "inputs" => {
            "clip_name" => "qwen_2.5_vl_7b_fp8_scaled.safetensors",
            "type" => "qwen_image",
            "device" => "default"
          },
          "class_type" => "CLIPLoader",
          "_meta" => {
            "title" => "Load CLIP"
          }
        },
        "115:110" => {
          "inputs" => {
            "prompt" => "",
            "clip" => [
              "115:38",
              0
            ],
            "vae" => [
              "115:39",
              0
            ],
            "image1" => [
              "115:93",
              0
            ]
          },
          "class_type" => "TextEncodeQwenImageEditPlus",
          "_meta" => {
            "title" => "TextEncodeQwenImageEditPlus"
          }
        },
        "115:66" => {
          "inputs" => {
            "shift" => 3,
            "model" => [
              "115:89",
              0
            ]
          },
          "class_type" => "ModelSamplingAuraFlow",
          "_meta" => {
            "title" => "ModelSamplingAuraFlow"
          }
        },
        "115:8" => {
          "inputs" => {
            "samples" => [
              "115:3",
              0
            ],
            "vae" => [
              "115:39",
              0
            ]
          },
          "class_type" => "VAEDecode",
          "_meta" => {
            "title" => "VAE Decode"
          }
        },
        "115:116" => {
          "inputs" => {
            "images" => [
              "115:8",
              0
            ]
          },
          "class_type" => "PreviewImage",
          "_meta" => {
            "title" => "Preview Image"
          }
        },
        "115:3" => {
          "inputs" => {
            "seed" => 1118877715456453,
            "steps" => 4,
            "cfg" => 1,
            "sampler_name" => "euler",
            "scheduler" => "simple",
            "denoise" => 1,
            "model" => [
              "115:75",
              0
            ],
            "positive" => [
              "115:111",
              0
            ],
            "negative" => [
              "115:110",
              0
            ],
            "latent_image" => [
              "115:88",
              0
            ]
          },
          "class_type" => "KSampler",
          "_meta" => {
            "title" => "KSampler"
          }
        },
        "115:111" => {
          "inputs" => {
            "prompt" => extraction_prompt,
            "clip" => [
              "115:38",
              0
            ],
            "vae" => [
              "115:39",
              0
            ],
            "image1" => [
              "115:93",
              0
            ]
          },
          "class_type" => "TextEncodeQwenImageEditPlus",
          "_meta" => {
            "title" => "TextEncodeQwenImageEditPlus"
          }
        },
        "115:89" => {
          "inputs" => {
            "lora_name" => "Qwen-Image-Lightning-4steps-V1.0.safetensors",
            "strength_model" => 1,
            "model" => [
              "115:37",
              0
            ]
          },
          "class_type" => "LoraLoaderModelOnly",
          "_meta" => {
            "title" => "LoraLoaderModelOnly"
          }
        },
        "115:88" => {
          "inputs" => {
            "pixels" => [
              "115:93",
              0
            ],
            "vae" => [
              "115:39",
              0
            ]
          },
          "class_type" => "VAEEncode",
          "_meta" => {
            "title" => "VAE Encode"
          }
        },
        "115:93" => {
          "inputs" => {
            "upscale_method" => "lanczos",
            "megapixels" => 1,
            "image" => [
              "78",
              0
            ]
          },
          "class_type" => "ImageScaleToTotalPixels",
          "_meta" => {
            "title" => "Scale Image to Total Pixels"
          }
        },
        "115:37" => {
          "inputs" => {
            "unet_name" => "qwen_image_edit_2509_fp8_e4m3fn.safetensors",
            "weight_dtype" => "default"
          },
          "class_type" => "UNETLoader",
          "_meta" => {
            "title" => "Load Diffusion Model"
          }
        },
        "115:112" => {
          "inputs" => {
            "width" => 720,
            "height" => 544,
            "batch_size" => 1
          },
          "class_type" => "EmptySD3LatentImage",
          "_meta" => {
            "title" => "EmptySD3LatentImage"
          }
        }
      }

      workflow
    end

    def submit_workflow(workflow_data, client_id: nil)
      base_uri = URI(base_url)
      http = Net::HTTP.new(base_uri.host, base_uri.port)
      http.open_timeout = 10
      http.read_timeout = 10

      # Use provided client_id for WebSocket tracking, or generate new one
      client_id ||= SecureRandom.uuid

      request = Net::HTTP::Post.new("/prompt")
      request["Content-Type"] = "application/json"
      request.body = {
        prompt: workflow_data,
        client_id: client_id
      }.to_json

      response = http.request(request)

      unless response.code == "200"
        raise StandardError, "ComfyUI API returned status #{response.code}: #{response.body}"
      end

      parsed = JSON.parse(response.body)
      job_id = parsed["prompt_id"]

      unless job_id.present?
        raise StandardError, "ComfyUI did not return a prompt_id: #{parsed.inspect}"
      end

      Rails.logger.info "ComfyUI workflow submitted (job: #{job_id})"
      job_id
    rescue JSON::ParserError => e
      Rails.logger.error "Failed to parse ComfyUI response: #{e.message}"
      raise StandardError, "Invalid response from ComfyUI API"
    end

    def poll_for_completion(job_id, max_attempts: 60, interval: 2)
      # Poll every 2 seconds for up to 2 minutes
      base_uri = URI(base_url)
      http = Net::HTTP.new(base_uri.host, base_uri.port)
      http.open_timeout = 5
      http.read_timeout = 5

      max_attempts.times do |attempt|
        request = Net::HTTP::Get.new("/history/#{job_id}")
        response = http.request(request)

        if response.code == "200"
          result = JSON.parse(response.body)

          # ComfyUI history format: { prompt_id: { "prompt": [...], "outputs": {...}, "status": {...} } }
          # If job is not in history yet, result will be empty {}
          job_data = result[job_id]

          if job_data && job_data.is_a?(Hash)
            status = job_data["status"]
            outputs = job_data["outputs"] || {}

            # Check if job is completed
            if status && (status["completed"] == true || status["status_str"] == "success")
              Rails.logger.info "ComfyUI job completed (job: #{job_id}, attempt: #{attempt + 1})"
              Rails.logger.info "ComfyUI outputs: #{outputs.inspect}"

              image_data = extract_image_from_outputs(outputs, http, base_uri)

              if image_data.nil?
                Rails.logger.error "ComfyUI returned no image data for job #{job_id}"
                raise StandardError, "ComfyUI did not return image data"
              end

              image_size = image_data.respond_to?(:bytesize) ? image_data.bytesize : image_data.size
              Rails.logger.info "ComfyUI returned image data: #{image_size} bytes (#{(image_size / 1024.0).round(2)} KB)"
              Rails.logger.info "Image data type: #{image_data.class}, encoding: #{image_data.respond_to?(:encoding) ? image_data.encoding : 'N/A'}"

              return {
                "success" => true,
                "job_id" => job_id,
                "outputs" => outputs,
                "image_data" => image_data
              }
            end

            # Check if job failed
            if status && status["status_str"] == "error"
              # Extract error message from status messages or use default
              error_msg = if status["messages"] && status["messages"].any?
                status["messages"].join("; ")
              else
                "Unknown error"
              end
              raise StandardError, "ComfyUI job failed: #{error_msg}"
            end
          end
          # If job_data is nil or empty, job is still in queue or processing
        end

        # Wait before next poll
        sleep interval unless attempt == max_attempts - 1
      end

      raise StandardError, "ComfyUI job timed out after #{max_attempts * interval} seconds"
    rescue JSON::ParserError => e
      Rails.logger.error "Failed to parse ComfyUI history response: #{e.message}"
      raise StandardError, "Invalid response from ComfyUI API"
    end

    # Wait for job completion via WebSocket (real-time, more efficient than polling)
    # Falls back to polling if WebSocket fails
    # @param job_id [String] The ComfyUI prompt_id (job identifier)
    # @param client_id [String] The client_id used when submitting the workflow (must match)
    # @param timeout [Integer] Maximum time to wait in seconds (default: 300)
    def wait_for_completion_via_websocket(job_id, client_id: nil, timeout: 300)
      require "websocket-client-simple"
      require "timeout"

      # Capture service instance BEFORE any blocks to ensure correct context
      # This ensures we have a reference to the service instance, not the WebSocket client
      service_instance = self

      # Use provided client_id or generate new one (should match workflow submission)
      client_id ||= SecureRandom.uuid

      ws_base_url = base_url.gsub(/^http/, "ws")
      ws_url = "#{ws_base_url}/ws?clientId=#{client_id}"

      Rails.logger.info "Connecting to ComfyUI WebSocket: #{ws_url}"

      result = nil
      error_occurred = false
      error_message = nil
      connection_closed = false

      # Use timeout to prevent hanging
      Timeout.timeout(timeout) do
        ws = WebSocket::Client::Simple.connect(ws_url)

        ws.on :open do
          Rails.logger.info "WebSocket connected to ComfyUI (waiting for job #{job_id})"
        end

        ws.on :message do |msg|
          begin
            # Handle both text and binary messages
            message_data = if msg.data.is_a?(String)
              JSON.parse(msg.data)
            else
              # Binary data (preview images) - ignore
              next
            end

            # Inline message handling to avoid method resolution issues in WebSocket callbacks
            # Check message type and handle accordingly
            next unless message_data.is_a?(Hash)

            case message_data["type"]
            when "executing"
              data = message_data["data"]
              if data && data["node"].nil? && data["prompt_id"] == job_id
                # Execution complete - fetch results
                Rails.logger.info "ComfyUI job completed via WebSocket (prompt_id: #{job_id})"
                extraction_result = service_instance.fetch_job_results_after_completion(job_id)
                if extraction_result
                  result = extraction_result
                  ws.close
                end
              end
            when "progress"
              # Progress updates - log for debugging
              progress_data = message_data["data"]
              Rails.logger.debug "ComfyUI progress: #{progress_data.inspect}"
            when "execution_error"
              error_data = message_data["data"]
              error_msg = error_data["error_message"] || error_data["message"] || "Unknown error"
              Rails.logger.error "ComfyUI execution error: #{error_msg}"
              error_occurred = true
              error_message = "ComfyUI execution error: #{error_msg}"
              ws.close
            when "execution_start"
              # Job started executing
              Rails.logger.debug "ComfyUI job started executing"
            when "execution_cached"
              # Node output was cached
              Rails.logger.debug "ComfyUI node output cached"
            end
          rescue JSON::ParserError
            # Binary data - ignore
            Rails.logger.debug "Received binary WebSocket message (preview image)"
          rescue StandardError => e
            Rails.logger.error "Error handling WebSocket message: #{e.message}"
            Rails.logger.error e.backtrace.first(5).join("\n")
            error_occurred = true
            error_message = e.message
            ws.close
          end
        end

        ws.on :error do |e|
          Rails.logger.error "WebSocket error: #{e.message}"
          error_occurred = true
          error_message = e.message
          connection_closed = true
        end

        ws.on :close do |e|
          Rails.logger.info "WebSocket connection closed"
          connection_closed = true
        end

        # Wait for result, error, or timeout
        start_time = Time.current
        loop do
          break if result || error_occurred || connection_closed
          break if (Time.current - start_time) > timeout

          sleep 0.1
        end

        ws.close unless connection_closed
      end

      if error_occurred
        raise StandardError, "WebSocket error: #{error_message}"
      end

      unless result
        raise StandardError, "WebSocket connection closed without result (job may still be processing)"
      end

      result
    rescue Timeout::Error
      Rails.logger.error "WebSocket extraction timed out after #{timeout} seconds"
      raise StandardError, "ComfyUI job timed out after #{timeout} seconds"
    rescue LoadError => e
      # Gem not installed - fallback to polling
      Rails.logger.warn "websocket-client-simple gem not available: #{e.message}"
      raise StandardError, "WebSocket client not available"
    rescue StandardError => e
      Rails.logger.error "WebSocket extraction failed: #{e.message}"
      raise
    end

    # Fetch job results after WebSocket completion notification
    def fetch_job_results_after_completion(job_id)
      base_uri = URI(base_url)
      http = Net::HTTP.new(base_uri.host, base_uri.port)
      http.open_timeout = 10
      http.read_timeout = 30

      # Get history
      request = Net::HTTP::Get.new("/history/#{job_id}")
      response = http.request(request)

      unless response.code == "200"
        raise StandardError, "Failed to fetch ComfyUI history: HTTP #{response.code}"
      end

      result = JSON.parse(response.body)
      job_data = result[job_id]

      unless job_data && job_data.is_a?(Hash)
        raise StandardError, "ComfyUI history does not contain job data for #{job_id}"
      end

      outputs = job_data["outputs"] || {}
      status = job_data["status"]

      # Check if job failed
      if status && status["status_str"] == "error"
        error_msg = if status["messages"] && status["messages"].any?
          status["messages"].join("; ")
        else
          "Unknown error"
        end
        raise StandardError, "ComfyUI job failed: #{error_msg}"
      end

      # Extract image data
      image_data = extract_image_from_outputs(outputs, http, base_uri)

      unless image_data
        raise StandardError, "ComfyUI did not return image data"
      end

      image_size = image_data.respond_to?(:bytesize) ? image_data.bytesize : image_data.size
      Rails.logger.info "ComfyUI returned image data: #{image_size} bytes (#{(image_size / 1024.0).round(2)} KB)"

      {
        "success" => true,
        "job_id" => job_id,
        "outputs" => outputs,
        "image_data" => image_data
      }
    rescue JSON::ParserError => e
      Rails.logger.error "Failed to parse ComfyUI history response: #{e.message}"
      raise StandardError, "Invalid response from ComfyUI API"
    end

    def extract_image_from_outputs(outputs, http, base_uri)
      # Extract image data from ComfyUI outputs
      # ComfyUI outputs format: { "60": { "images": [{ "filename": "...", "subfolder": "...", "type": "output" }] } }
      # Node "60" is the SaveImage node in our workflow

      Rails.logger.info "Extracting image from ComfyUI outputs: #{outputs.inspect}"

      return nil unless outputs.is_a?(Hash)

      if outputs.empty?
        Rails.logger.warn "ComfyUI outputs is empty hash"
        return nil
      end

      # Look for SaveImage node output (node "60")
      save_node = outputs["60"]
      if save_node && save_node["images"] && save_node["images"].is_a?(Array) && save_node["images"].any?
        image_info = save_node["images"].first
        filename = image_info["filename"]
        subfolder = image_info["subfolder"] || ""
        type = image_info["type"] || "output"

        # Download image from ComfyUI
        view_path = "/view"
        view_path += "?filename=#{URI.encode_www_form_component(filename)}"
        view_path += "&subfolder=#{URI.encode_www_form_component(subfolder)}" if subfolder.present?
        view_path += "&type=#{URI.encode_www_form_component(type)}"

        # Create a fresh HTTP connection for image download to avoid connection reuse issues
        image_http = Net::HTTP.new(base_uri.host, base_uri.port)
        image_http.open_timeout = 10
        image_http.read_timeout = 60  # Longer timeout for large images

        request = Net::HTTP::Get.new(view_path)
        response = image_http.request(request)

        if response.code == "200"
          Rails.logger.info "Downloaded extracted image from ComfyUI: #{filename}"

          # Read response body carefully - ensure we get the full body
          image_data = response.body

          # Check Content-Length header if available
          if response["Content-Length"]
            expected_size = response["Content-Length"].to_i
            actual_size = image_data.respond_to?(:bytesize) ? image_data.bytesize : image_data.size
            if actual_size != expected_size
              Rails.logger.error "⚠️  WARNING: Content-Length mismatch! Expected: #{expected_size} bytes, Got: #{actual_size} bytes"
            end
          end

          # Validate we got actual data
          if image_data.nil? || image_data.empty?
            Rails.logger.error "ComfyUI returned empty response body for #{filename}"
            return nil
          end

          # Force binary encoding to ensure image data is handled correctly
          image_data.force_encoding("BINARY") if image_data.respond_to?(:force_encoding)

          image_size = image_data.respond_to?(:bytesize) ? image_data.bytesize : image_data.size
          Rails.logger.info "Downloaded image size: #{image_size} bytes (#{(image_size / 1024.0).round(2)} KB)"

          # Validate minimum size
          if image_size < 10_000
            Rails.logger.error "⚠️  WARNING: Downloaded image is suspiciously small (#{image_size} bytes). Expected at least 50KB."
            return nil
          end

          # Validate PNG header
          if image_size >= 8
            png_header = image_data[0..7].bytes
            is_png = png_header == [ 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A ]
            if is_png
              Rails.logger.info "✓ Valid PNG header confirmed"
            else
              Rails.logger.error "⚠️  ERROR: Invalid PNG header (first 8 bytes: #{png_header.inspect}). Image data is corrupted."
              return nil
            end
          end

          return image_data
        else
          Rails.logger.error "Failed to download image from ComfyUI: HTTP #{response.code}"
          return nil
        end
      end

      # Fallback: try to find any image output
      outputs.each do |_node_id, node_output|
        next unless node_output.is_a?(Hash) && node_output["images"]

        images = node_output["images"]
        images = [ images ] unless images.is_a?(Array)

        images.each do |image_info|
          next unless image_info.is_a?(Hash) && image_info["filename"]

          filename = image_info["filename"]
          subfolder = image_info["subfolder"] || ""
          type = image_info["type"] || "output"

          view_path = "/view"
          view_path += "?filename=#{URI.encode_www_form_component(filename)}"
          view_path += "&subfolder=#{URI.encode_www_form_component(subfolder)}" if subfolder.present?
          view_path += "&type=#{URI.encode_www_form_component(type)}"

          # Create a fresh HTTP connection for image download to avoid connection reuse issues
          image_http = Net::HTTP.new(base_uri.host, base_uri.port)
          image_http.open_timeout = 10
          image_http.read_timeout = 60  # Longer timeout for large images

          request = Net::HTTP::Get.new(view_path)
          response = image_http.request(request)

          if response.code == "200"
            Rails.logger.info "Downloaded extracted image from ComfyUI: #{filename}"

            # Read response body carefully - ensure we get the full body
            image_data = response.body

            # Check Content-Length header if available
            if response["Content-Length"]
              expected_size = response["Content-Length"].to_i
              actual_size = image_data.respond_to?(:bytesize) ? image_data.bytesize : image_data.size
              if actual_size != expected_size
                Rails.logger.error "⚠️  WARNING: Content-Length mismatch! Expected: #{expected_size} bytes, Got: #{actual_size} bytes"
              end
            end

            # Validate we got actual data
            if image_data.nil? || image_data.empty?
              Rails.logger.error "ComfyUI returned empty response body for #{filename}"
              next
            end

            # Force binary encoding to ensure image data is handled correctly
            image_data.force_encoding("BINARY") if image_data.respond_to?(:force_encoding)

            image_size = image_data.respond_to?(:bytesize) ? image_data.bytesize : image_data.size
            Rails.logger.info "Downloaded image size: #{image_size} bytes (#{(image_size / 1024.0).round(2)} KB)"

            # Validate minimum size
            if image_size < 10_000
              Rails.logger.error "⚠️  WARNING: Downloaded image is suspiciously small (#{image_size} bytes). Expected at least 50KB."
              next
            end

            # Validate PNG header
            if image_size >= 8
              png_header = image_data[0..7].bytes
              is_png = png_header == [ 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A ]
              if is_png
                Rails.logger.info "✓ Valid PNG header confirmed"
              else
                Rails.logger.error "⚠️  ERROR: Invalid PNG header (first 8 bytes: #{png_header.inspect}). Image data is corrupted."
                next
              end
            end

            return image_data
          end
        end
      end

      Rails.logger.warn "No image found in ComfyUI outputs"
      nil
    end
  end
end
