# Service for integrating with ComfyUI API for stock photo extraction
# ComfyUI is a node-based Stable Diffusion UI that supports image editing
class ComfyUiService
  def self.base_url
    ENV["COMFY_UI_API_URL"] || "http://localhost:8188"
  end

  class << self
    # Extract stock photo from original image using ComfyUI + Qwen Image Edit
    # @param original_image_blob [ActiveStorage::Blob] The original image blob
    # @param extraction_prompt [String] The extraction prompt generated by ExtractionPromptBuilder
    # @return [Hash] Result containing extracted image data or error
    def extract_stock_photo(original_image_blob:, extraction_prompt:)
      Rails.logger.info "Starting ComfyUI stock photo extraction"

      # Validate inputs
      unless original_image_blob.present?
        raise ArgumentError, "Original image blob is required"
      end

      unless extraction_prompt.present?
        raise ArgumentError, "Extraction prompt is required"
      end

      # Check ComfyUI availability
      check_comfyui_availability!

      # Upload image to ComfyUI and get filename
      image_filename = upload_image(original_image_blob)

      # Build workflow payload using actual workflow template
      workflow_data = build_workflow(image_filename, extraction_prompt)

      # Submit to ComfyUI
      job_id = submit_workflow(workflow_data)

      # Poll for completion
      result = poll_for_completion(job_id)

      Rails.logger.info "ComfyUI extraction completed successfully (job: #{job_id})"
      result
    rescue ArgumentError => e
      # Re-raise ArgumentError - these are validation errors that callers should handle
      raise
    rescue StandardError => e
      Rails.logger.error "ComfyUI extraction failed: #{e.message}"
      Rails.logger.error e.backtrace.first(10).join("\n")
      { "error" => e.message, "success" => false }
    end

    private

    def check_comfyui_availability!
      base_uri = URI(base_url)

      Rails.logger.info "Checking ComfyUI availability at #{base_url}..."

      begin
        http = Net::HTTP.new(base_uri.host, base_uri.port)
        http.open_timeout = 3
        http.read_timeout = 3

        # Check if ComfyUI is up (simple GET to root)
        response = http.get("/")
        unless response.code.to_i < 500
          raise StandardError, "ComfyUI API returned status #{response.code}"
        end

        Rails.logger.info "✓ ComfyUI is available at #{base_url}"
      rescue Errno::ECONNREFUSED, Errno::EHOSTUNREACH, SocketError => e
        Rails.logger.error "Cannot connect to ComfyUI at #{base_url}: #{e.message}"
        raise StandardError, "ComfyUI service is not available at #{base_url}. Please ensure ComfyUI is running."
      rescue Net::ReadTimeout, Net::OpenTimeout, Timeout::Error => e
        Rails.logger.error "Timeout connecting to ComfyUI: #{e.message}"
        raise StandardError, "Timeout connecting to ComfyUI service. Please check if ComfyUI is running."
      rescue StandardError => e
        raise e if e.message.include?("ComfyUI")
        Rails.logger.error "Error checking ComfyUI availability: #{e.message}"
        raise StandardError, "Failed to verify ComfyUI availability: #{e.message}"
      end
    end

    def upload_image(blob)
      # Upload image to ComfyUI and return filename
      base_uri = URI(base_url)
      http = Net::HTTP.new(base_uri.host, base_uri.port)
      http.open_timeout = 10
      http.read_timeout = 10

      image_data = blob.download
      extension = blob.filename.extension.presence || "jpg"
      filename = "#{SecureRandom.hex(8)}.#{extension}"

      request = Net::HTTP::Post.new("/upload/image")
      form_data = [
        [ "image", image_data, { filename: filename, content_type: blob.content_type } ]
      ]
      request.set_form(form_data, "multipart/form-data")

      response = http.request(request)

      unless response.code == "200"
        raise StandardError, "ComfyUI image upload returned status #{response.code}: #{response.body}"
      end

      parsed = JSON.parse(response.body)
      uploaded_filename = parsed["name"] || filename

      Rails.logger.info "Image uploaded to ComfyUI: #{uploaded_filename}"
      uploaded_filename
    rescue JSON::ParserError => e
      Rails.logger.error "Failed to parse ComfyUI upload response: #{e.message}"
      raise StandardError, "Invalid response from ComfyUI upload API"
    end

    def build_workflow(image_filename, extraction_prompt)
      # Build ComfyUI workflow using the actual workflow template
      # This workflow uses Qwen Image Edit for stock photo extraction
      workflow = {
        "60" => {
          "inputs" => {
            "filename_prefix" => "ComfyUI",
            "images" => [
              "115:8",
              0
            ]
          },
          "class_type" => "SaveImage",
          "_meta" => {
            "title" => "Save Image"
          }
        },
        "78" => {
          "inputs" => {
            "image" => image_filename
          },
          "class_type" => "LoadImage",
          "_meta" => {
            "title" => "Load Image"
          }
        },
        "115:75" => {
          "inputs" => {
            "strength" => 1,
            "model" => [
              "115:66",
              0
            ]
          },
          "class_type" => "CFGNorm",
          "_meta" => {
            "title" => "CFGNorm"
          }
        },
        "115:39" => {
          "inputs" => {
            "vae_name" => "qwen_image_vae.safetensors"
          },
          "class_type" => "VAELoader",
          "_meta" => {
            "title" => "Load VAE"
          }
        },
        "115:38" => {
          "inputs" => {
            "clip_name" => "qwen_2.5_vl_7b_fp8_scaled.safetensors",
            "type" => "qwen_image",
            "device" => "default"
          },
          "class_type" => "CLIPLoader",
          "_meta" => {
            "title" => "Load CLIP"
          }
        },
        "115:110" => {
          "inputs" => {
            "prompt" => "",
            "clip" => [
              "115:38",
              0
            ],
            "vae" => [
              "115:39",
              0
            ],
            "image1" => [
              "115:93",
              0
            ]
          },
          "class_type" => "TextEncodeQwenImageEditPlus",
          "_meta" => {
            "title" => "TextEncodeQwenImageEditPlus"
          }
        },
        "115:66" => {
          "inputs" => {
            "shift" => 3,
            "model" => [
              "115:89",
              0
            ]
          },
          "class_type" => "ModelSamplingAuraFlow",
          "_meta" => {
            "title" => "ModelSamplingAuraFlow"
          }
        },
        "115:8" => {
          "inputs" => {
            "samples" => [
              "115:3",
              0
            ],
            "vae" => [
              "115:39",
              0
            ]
          },
          "class_type" => "VAEDecode",
          "_meta" => {
            "title" => "VAE Decode"
          }
        },
        "115:116" => {
          "inputs" => {
            "images" => [
              "115:8",
              0
            ]
          },
          "class_type" => "PreviewImage",
          "_meta" => {
            "title" => "Preview Image"
          }
        },
        "115:3" => {
          "inputs" => {
            "seed" => 1118877715456453,
            "steps" => 4,
            "cfg" => 1,
            "sampler_name" => "euler",
            "scheduler" => "simple",
            "denoise" => 1,
            "model" => [
              "115:75",
              0
            ],
            "positive" => [
              "115:111",
              0
            ],
            "negative" => [
              "115:110",
              0
            ],
            "latent_image" => [
              "115:88",
              0
            ]
          },
          "class_type" => "KSampler",
          "_meta" => {
            "title" => "KSampler"
          }
        },
        "115:111" => {
          "inputs" => {
            "prompt" => extraction_prompt,
            "clip" => [
              "115:38",
              0
            ],
            "vae" => [
              "115:39",
              0
            ],
            "image1" => [
              "115:93",
              0
            ]
          },
          "class_type" => "TextEncodeQwenImageEditPlus",
          "_meta" => {
            "title" => "TextEncodeQwenImageEditPlus"
          }
        },
        "115:89" => {
          "inputs" => {
            "lora_name" => "Qwen-Image-Lightning-4steps-V1.0.safetensors",
            "strength_model" => 1,
            "model" => [
              "115:37",
              0
            ]
          },
          "class_type" => "LoraLoaderModelOnly",
          "_meta" => {
            "title" => "LoraLoaderModelOnly"
          }
        },
        "115:88" => {
          "inputs" => {
            "pixels" => [
              "115:93",
              0
            ],
            "vae" => [
              "115:39",
              0
            ]
          },
          "class_type" => "VAEEncode",
          "_meta" => {
            "title" => "VAE Encode"
          }
        },
        "115:93" => {
          "inputs" => {
            "upscale_method" => "lanczos",
            "megapixels" => 1,
            "image" => [
              "78",
              0
            ]
          },
          "class_type" => "ImageScaleToTotalPixels",
          "_meta" => {
            "title" => "Scale Image to Total Pixels"
          }
        },
        "115:37" => {
          "inputs" => {
            "unet_name" => "qwen_image_edit_2509_fp8_e4m3fn.safetensors",
            "weight_dtype" => "default"
          },
          "class_type" => "UNETLoader",
          "_meta" => {
            "title" => "Load Diffusion Model"
          }
        },
        "115:112" => {
          "inputs" => {
            "width" => 720,
            "height" => 544,
            "batch_size" => 1
          },
          "class_type" => "EmptySD3LatentImage",
          "_meta" => {
            "title" => "EmptySD3LatentImage"
          }
        }
      }

      workflow
    end

    def submit_workflow(workflow_data)
      base_uri = URI(base_url)
      http = Net::HTTP.new(base_uri.host, base_uri.port)
      http.open_timeout = 10
      http.read_timeout = 10

      request = Net::HTTP::Post.new("/prompt")
      request["Content-Type"] = "application/json"
      request.body = {
        prompt: workflow_data,
        client_id: SecureRandom.uuid
      }.to_json

      response = http.request(request)

      unless response.code == "200"
        raise StandardError, "ComfyUI API returned status #{response.code}: #{response.body}"
      end

      parsed = JSON.parse(response.body)
      job_id = parsed["prompt_id"]

      unless job_id.present?
        raise StandardError, "ComfyUI did not return a prompt_id: #{parsed.inspect}"
      end

      Rails.logger.info "ComfyUI workflow submitted (job: #{job_id})"
      job_id
    rescue JSON::ParserError => e
      Rails.logger.error "Failed to parse ComfyUI response: #{e.message}"
      raise StandardError, "Invalid response from ComfyUI API"
    end

    def poll_for_completion(job_id, max_attempts: 60, interval: 2)
      # Poll every 2 seconds for up to 2 minutes
      base_uri = URI(base_url)
      http = Net::HTTP.new(base_uri.host, base_uri.port)
      http.open_timeout = 5
      http.read_timeout = 5

      max_attempts.times do |attempt|
        request = Net::HTTP::Get.new("/history/#{job_id}")
        response = http.request(request)

        if response.code == "200"
          result = JSON.parse(response.body)

          # ComfyUI history format: { prompt_id: { "prompt": [...], "outputs": {...}, "status": {...} } }
          # If job is not in history yet, result will be empty {}
          job_data = result[job_id]

          if job_data && job_data.is_a?(Hash)
            status = job_data["status"]
            outputs = job_data["outputs"] || {}

            # Check if job is completed
            if status && (status["completed"] == true || status["status_str"] == "success")
              Rails.logger.info "ComfyUI job completed (job: #{job_id}, attempt: #{attempt + 1})"

              image_data = extract_image_from_outputs(outputs, http, base_uri)

              return {
                "success" => true,
                "job_id" => job_id,
                "outputs" => outputs,
                "image_data" => image_data
              }
            end

            # Check if job failed
            if status && status["status_str"] == "error"
              # Extract error message from status messages or use default
              error_msg = if status["messages"] && status["messages"].any?
                status["messages"].join("; ")
              else
                "Unknown error"
              end
              raise StandardError, "ComfyUI job failed: #{error_msg}"
            end
          end
          # If job_data is nil or empty, job is still in queue or processing
        end

        # Wait before next poll
        sleep interval unless attempt == max_attempts - 1
      end

      raise StandardError, "ComfyUI job timed out after #{max_attempts * interval} seconds"
    rescue JSON::ParserError => e
      Rails.logger.error "Failed to parse ComfyUI history response: #{e.message}"
      raise StandardError, "Invalid response from ComfyUI API"
    end

    def extract_image_from_outputs(outputs, http, base_uri)
      # Extract image data from ComfyUI outputs
      # ComfyUI outputs format: { "60": { "images": [{ "filename": "...", "subfolder": "...", "type": "output" }] } }
      # Node "60" is the SaveImage node in our workflow

      return nil unless outputs.is_a?(Hash)

      # Look for SaveImage node output (node "60")
      save_node = outputs["60"]
      if save_node && save_node["images"] && save_node["images"].is_a?(Array) && save_node["images"].any?
        image_info = save_node["images"].first
        filename = image_info["filename"]
        subfolder = image_info["subfolder"] || ""
        type = image_info["type"] || "output"

        # Download image from ComfyUI
        view_path = "/view"
        view_path += "?filename=#{URI.encode_www_form_component(filename)}"
        view_path += "&subfolder=#{URI.encode_www_form_component(subfolder)}" if subfolder.present?
        view_path += "&type=#{URI.encode_www_form_component(type)}"

        request = Net::HTTP::Get.new(view_path)
        response = http.request(request)

        if response.code == "200"
          Rails.logger.info "Downloaded extracted image from ComfyUI: #{filename}"
          return response.body
        else
          Rails.logger.error "Failed to download image from ComfyUI: #{response.code}"
          return nil
        end
      end

      # Fallback: try to find any image output
      outputs.each do |_node_id, node_output|
        next unless node_output.is_a?(Hash) && node_output["images"]

        images = node_output["images"]
        images = [ images ] unless images.is_a?(Array)

        images.each do |image_info|
          next unless image_info.is_a?(Hash) && image_info["filename"]

          filename = image_info["filename"]
          subfolder = image_info["subfolder"] || ""
          type = image_info["type"] || "output"

          view_path = "/view"
          view_path += "?filename=#{URI.encode_www_form_component(filename)}"
          view_path += "&subfolder=#{URI.encode_www_form_component(subfolder)}" if subfolder.present?
          view_path += "&type=#{URI.encode_www_form_component(type)}"

          request = Net::HTTP::Get.new(view_path)
          response = http.request(request)

          if response.code == "200"
            Rails.logger.info "Downloaded extracted image from ComfyUI: #{filename}"
            return response.body
          end
        end
      end

      Rails.logger.warn "No image found in ComfyUI outputs"
      nil
    end
  end
end
