// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AppConfig {
    pub id: u64,
    pub notes_callback: String,
    pub typewars_callback: String,
    pub admin_callback: String,
    pub deck_origin: String,
}

impl __sdk::InModule for AppConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AppConfig`.
///
/// Provides typed access to columns for query building.
pub struct AppConfigCols {
    pub id: __sdk::__query_builder::Col<AppConfig, u64>,
    pub notes_callback: __sdk::__query_builder::Col<AppConfig, String>,
    pub typewars_callback: __sdk::__query_builder::Col<AppConfig, String>,
    pub admin_callback: __sdk::__query_builder::Col<AppConfig, String>,
    pub deck_origin: __sdk::__query_builder::Col<AppConfig, String>,
}

impl __sdk::__query_builder::HasCols for AppConfig {
    type Cols = AppConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AppConfigCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            notes_callback: __sdk::__query_builder::Col::new(table_name, "notes_callback"),
            typewars_callback: __sdk::__query_builder::Col::new(table_name, "typewars_callback"),
            admin_callback: __sdk::__query_builder::Col::new(table_name, "admin_callback"),
            deck_origin: __sdk::__query_builder::Col::new(table_name, "deck_origin"),
        }
    }
}

/// Indexed column accessor struct for the table `AppConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct AppConfigIxCols {
    pub id: __sdk::__query_builder::IxCol<AppConfig, u64>,
}

impl __sdk::__query_builder::HasIxCols for AppConfig {
    type IxCols = AppConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AppConfigIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AppConfig {}
