// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::app_config_type::AppConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `app_config`.
///
/// Obtain a handle from the [`AppConfigTableAccess::app_config`] method on [`super::RemoteTables`],
/// like `ctx.db.app_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.app_config().on_insert(...)`.
pub struct AppConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<AppConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `app_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AppConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AppConfigTableHandle`], which mediates access to the table `app_config`.
    fn app_config(&self) -> AppConfigTableHandle<'_>;
}

impl AppConfigTableAccess for super::RemoteTables {
    fn app_config(&self) -> AppConfigTableHandle<'_> {
        AppConfigTableHandle {
            imp: self.imp.get_table::<AppConfig>("app_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AppConfigInsertCallbackId(__sdk::CallbackId);
pub struct AppConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AppConfigTableHandle<'ctx> {
    type Row = AppConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AppConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AppConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AppConfigInsertCallbackId {
        AppConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AppConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AppConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AppConfigDeleteCallbackId {
        AppConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AppConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AppConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AppConfigTableHandle<'ctx> {
    type UpdateCallbackId = AppConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AppConfigUpdateCallbackId {
        AppConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AppConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `app_config`,
/// which allows point queries on the field of the same name
/// via the [`AppConfigIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.app_config().id().find(...)`.
pub struct AppConfigIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AppConfig, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AppConfigTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `app_config`.
    pub fn id(&self) -> AppConfigIdUnique<'ctx> {
        AppConfigIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AppConfigIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AppConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AppConfig>("app_config");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AppConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AppConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AppConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait app_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AppConfig`.
    fn app_config(&self) -> __sdk::__query_builder::Table<AppConfig>;
}

impl app_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn app_config(&self) -> __sdk::__query_builder::Table<AppConfig> {
        __sdk::__query_builder::Table::new("app_config")
    }
}
