// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendLogEventArgs {
    pub container: String,
    pub ts_micros: i64,
    pub level: String,
    pub text: String,
}

impl From<AppendLogEventArgs> for super::Reducer {
    fn from(args: AppendLogEventArgs) -> Self {
        Self::AppendLogEvent {
            container: args.container,
            ts_micros: args.ts_micros,
            level: args.level,
            text: args.text,
        }
    }
}

impl __sdk::InModule for AppendLogEventArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_log_event`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_log_event {
    /// Request that the remote module invoke the reducer `append_log_event` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append_log_event:append_log_event_then`] to run a callback after the reducer completes.
    fn append_log_event(
        &self,
        container: String,
        ts_micros: i64,
        level: String,
        text: String,
    ) -> __sdk::Result<()> {
        self.append_log_event_then(container, ts_micros, level, text, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `append_log_event` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_log_event_then(
        &self,
        container: String,
        ts_micros: i64,
        level: String,
        text: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append_log_event for super::RemoteReducers {
    fn append_log_event_then(
        &self,
        container: String,
        ts_micros: i64,
        level: String,
        text: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AppendLogEventArgs {
                container,
                ts_micros,
                level,
                text,
            },
            callback,
        )
    }
}
