// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AuthToken {
    pub token: String,
    pub email: String,
    pub created_at: __sdk::Timestamp,
    pub expires_at: __sdk::Timestamp,
    pub used_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for AuthToken {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AuthToken`.
///
/// Provides typed access to columns for query building.
pub struct AuthTokenCols {
    pub token: __sdk::__query_builder::Col<AuthToken, String>,
    pub email: __sdk::__query_builder::Col<AuthToken, String>,
    pub created_at: __sdk::__query_builder::Col<AuthToken, __sdk::Timestamp>,
    pub expires_at: __sdk::__query_builder::Col<AuthToken, __sdk::Timestamp>,
    pub used_at: __sdk::__query_builder::Col<AuthToken, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for AuthToken {
    type Cols = AuthTokenCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AuthTokenCols {
            token: __sdk::__query_builder::Col::new(table_name, "token"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            used_at: __sdk::__query_builder::Col::new(table_name, "used_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AuthToken`.
///
/// Provides typed access to indexed columns for query building.
pub struct AuthTokenIxCols {
    pub token: __sdk::__query_builder::IxCol<AuthToken, String>,
}

impl __sdk::__query_builder::HasIxCols for AuthToken {
    type IxCols = AuthTokenIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AuthTokenIxCols {
            token: __sdk::__query_builder::IxCol::new(table_name, "token"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AuthToken {}
