// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::comment_type::Comment;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `comment`.
///
/// Obtain a handle from the [`CommentTableAccess::comment`] method on [`super::RemoteTables`],
/// like `ctx.db.comment()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.comment().on_insert(...)`.
pub struct CommentTableHandle<'ctx> {
    imp: __sdk::TableHandle<Comment>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `comment`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CommentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CommentTableHandle`], which mediates access to the table `comment`.
    fn comment(&self) -> CommentTableHandle<'_>;
}

impl CommentTableAccess for super::RemoteTables {
    fn comment(&self) -> CommentTableHandle<'_> {
        CommentTableHandle {
            imp: self.imp.get_table::<Comment>("comment"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CommentInsertCallbackId(__sdk::CallbackId);
pub struct CommentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CommentTableHandle<'ctx> {
    type Row = Comment;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Comment> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CommentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CommentInsertCallbackId {
        CommentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CommentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CommentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CommentDeleteCallbackId {
        CommentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CommentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CommentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CommentTableHandle<'ctx> {
    type UpdateCallbackId = CommentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CommentUpdateCallbackId {
        CommentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CommentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `comment`,
/// which allows point queries on the field of the same name
/// via the [`CommentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.comment().id().find(...)`.
pub struct CommentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Comment, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CommentTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `comment`.
    pub fn id(&self) -> CommentIdUnique<'ctx> {
        CommentIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CommentIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Comment> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Comment>("comment");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Comment>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Comment>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Comment`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait commentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Comment`.
    fn comment(&self) -> __sdk::__query_builder::Table<Comment>;
}

impl commentQueryTableAccess for __sdk::QueryTableAccessor {
    fn comment(&self) -> __sdk::__query_builder::Table<Comment> {
        __sdk::__query_builder::Table::new("comment")
    }
}
