// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Comment {
    pub id: u64,
    pub post_slug: String,
    pub author_name: String,
    pub body: String,
    pub created_at: __sdk::Timestamp,
    pub status: String,
    pub submitter: __sdk::Identity,
}

impl __sdk::InModule for Comment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Comment`.
///
/// Provides typed access to columns for query building.
pub struct CommentCols {
    pub id: __sdk::__query_builder::Col<Comment, u64>,
    pub post_slug: __sdk::__query_builder::Col<Comment, String>,
    pub author_name: __sdk::__query_builder::Col<Comment, String>,
    pub body: __sdk::__query_builder::Col<Comment, String>,
    pub created_at: __sdk::__query_builder::Col<Comment, __sdk::Timestamp>,
    pub status: __sdk::__query_builder::Col<Comment, String>,
    pub submitter: __sdk::__query_builder::Col<Comment, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for Comment {
    type Cols = CommentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CommentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            post_slug: __sdk::__query_builder::Col::new(table_name, "post_slug"),
            author_name: __sdk::__query_builder::Col::new(table_name, "author_name"),
            body: __sdk::__query_builder::Col::new(table_name, "body"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            submitter: __sdk::__query_builder::Col::new(table_name, "submitter"),
        }
    }
}

/// Indexed column accessor struct for the table `Comment`.
///
/// Provides typed access to indexed columns for query building.
pub struct CommentIxCols {
    pub id: __sdk::__query_builder::IxCol<Comment, u64>,
    pub post_slug: __sdk::__query_builder::IxCol<Comment, String>,
    pub submitter: __sdk::__query_builder::IxCol<Comment, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Comment {
    type IxCols = CommentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CommentIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            post_slug: __sdk::__query_builder::IxCol::new(table_name, "post_slug"),
            submitter: __sdk::__query_builder::IxCol::new(table_name, "submitter"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Comment {}
