// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ContainerStatus {
    pub name: String,
    pub status: String,
    pub image: String,
    pub uptime_s: u64,
    pub mem_used_mb: u32,
    pub mem_limit_mb: u32,
    pub restart_count: u32,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for ContainerStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ContainerStatus`.
///
/// Provides typed access to columns for query building.
pub struct ContainerStatusCols {
    pub name: __sdk::__query_builder::Col<ContainerStatus, String>,
    pub status: __sdk::__query_builder::Col<ContainerStatus, String>,
    pub image: __sdk::__query_builder::Col<ContainerStatus, String>,
    pub uptime_s: __sdk::__query_builder::Col<ContainerStatus, u64>,
    pub mem_used_mb: __sdk::__query_builder::Col<ContainerStatus, u32>,
    pub mem_limit_mb: __sdk::__query_builder::Col<ContainerStatus, u32>,
    pub restart_count: __sdk::__query_builder::Col<ContainerStatus, u32>,
    pub updated_at: __sdk::__query_builder::Col<ContainerStatus, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ContainerStatus {
    type Cols = ContainerStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContainerStatusCols {
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            image: __sdk::__query_builder::Col::new(table_name, "image"),
            uptime_s: __sdk::__query_builder::Col::new(table_name, "uptime_s"),
            mem_used_mb: __sdk::__query_builder::Col::new(table_name, "mem_used_mb"),
            mem_limit_mb: __sdk::__query_builder::Col::new(table_name, "mem_limit_mb"),
            restart_count: __sdk::__query_builder::Col::new(table_name, "restart_count"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ContainerStatus`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContainerStatusIxCols {
    pub name: __sdk::__query_builder::IxCol<ContainerStatus, String>,
}

impl __sdk::__query_builder::HasIxCols for ContainerStatus {
    type IxCols = ContainerStatusIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContainerStatusIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ContainerStatus {}
