// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::container_status_type::ContainerStatus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `container_status`.
///
/// Obtain a handle from the [`ContainerStatusTableAccess::container_status`] method on [`super::RemoteTables`],
/// like `ctx.db.container_status()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.container_status().on_insert(...)`.
pub struct ContainerStatusTableHandle<'ctx> {
    imp: __sdk::TableHandle<ContainerStatus>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `container_status`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ContainerStatusTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ContainerStatusTableHandle`], which mediates access to the table `container_status`.
    fn container_status(&self) -> ContainerStatusTableHandle<'_>;
}

impl ContainerStatusTableAccess for super::RemoteTables {
    fn container_status(&self) -> ContainerStatusTableHandle<'_> {
        ContainerStatusTableHandle {
            imp: self.imp.get_table::<ContainerStatus>("container_status"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ContainerStatusInsertCallbackId(__sdk::CallbackId);
pub struct ContainerStatusDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ContainerStatusTableHandle<'ctx> {
    type Row = ContainerStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ContainerStatus> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ContainerStatusInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContainerStatusInsertCallbackId {
        ContainerStatusInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ContainerStatusInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ContainerStatusDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContainerStatusDeleteCallbackId {
        ContainerStatusDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ContainerStatusDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ContainerStatusUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ContainerStatusTableHandle<'ctx> {
    type UpdateCallbackId = ContainerStatusUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ContainerStatusUpdateCallbackId {
        ContainerStatusUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ContainerStatusUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `name` unique index on the table `container_status`,
/// which allows point queries on the field of the same name
/// via the [`ContainerStatusNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.container_status().name().find(...)`.
pub struct ContainerStatusNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ContainerStatus, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ContainerStatusTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `container_status`.
    pub fn name(&self) -> ContainerStatusNameUnique<'ctx> {
        ContainerStatusNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ContainerStatusNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<ContainerStatus> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ContainerStatus>("container_status");
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ContainerStatus>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ContainerStatus>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ContainerStatus`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait container_statusQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ContainerStatus`.
    fn container_status(&self) -> __sdk::__query_builder::Table<ContainerStatus>;
}

impl container_statusQueryTableAccess for __sdk::QueryTableAccessor {
    fn container_status(&self) -> __sdk::__query_builder::Table<ContainerStatus> {
        __sdk::__query_builder::Table::new("container_status")
    }
}
