// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteCommentArgs {
    pub id: u64,
}

impl From<DeleteCommentArgs> for super::Reducer {
    fn from(args: DeleteCommentArgs) -> Self {
        Self::DeleteComment { id: args.id }
    }
}

impl __sdk::InModule for DeleteCommentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_comment`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_comment {
    /// Request that the remote module invoke the reducer `delete_comment` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`delete_comment:delete_comment_then`] to run a callback after the reducer completes.
    fn delete_comment(&self, id: u64) -> __sdk::Result<()> {
        self.delete_comment_then(id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `delete_comment` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_comment_then(
        &self,
        id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_comment for super::RemoteReducers {
    fn delete_comment_then(
        &self,
        id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteCommentArgs { id }, callback)
    }
}
