// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::generate_job_type::GenerateJob;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `generate_job`.
///
/// Obtain a handle from the [`GenerateJobTableAccess::generate_job`] method on [`super::RemoteTables`],
/// like `ctx.db.generate_job()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.generate_job().on_insert(...)`.
pub struct GenerateJobTableHandle<'ctx> {
    imp: __sdk::TableHandle<GenerateJob>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `generate_job`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GenerateJobTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GenerateJobTableHandle`], which mediates access to the table `generate_job`.
    fn generate_job(&self) -> GenerateJobTableHandle<'_>;
}

impl GenerateJobTableAccess for super::RemoteTables {
    fn generate_job(&self) -> GenerateJobTableHandle<'_> {
        GenerateJobTableHandle {
            imp: self.imp.get_table::<GenerateJob>("generate_job"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GenerateJobInsertCallbackId(__sdk::CallbackId);
pub struct GenerateJobDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GenerateJobTableHandle<'ctx> {
    type Row = GenerateJob;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GenerateJob> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GenerateJobInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GenerateJobInsertCallbackId {
        GenerateJobInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GenerateJobInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GenerateJobDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GenerateJobDeleteCallbackId {
        GenerateJobDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GenerateJobDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GenerateJobUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GenerateJobTableHandle<'ctx> {
    type UpdateCallbackId = GenerateJobUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GenerateJobUpdateCallbackId {
        GenerateJobUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GenerateJobUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `generate_job`,
/// which allows point queries on the field of the same name
/// via the [`GenerateJobIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.generate_job().id().find(...)`.
pub struct GenerateJobIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GenerateJob, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GenerateJobTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `generate_job`.
    pub fn id(&self) -> GenerateJobIdUnique<'ctx> {
        GenerateJobIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GenerateJobIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GenerateJob> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GenerateJob>("generate_job");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GenerateJob>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GenerateJob>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GenerateJob`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait generate_jobQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GenerateJob`.
    fn generate_job(&self) -> __sdk::__query_builder::Table<GenerateJob>;
}

impl generate_jobQueryTableAccess for __sdk::QueryTableAccessor {
    fn generate_job(&self) -> __sdk::__query_builder::Table<GenerateJob> {
        __sdk::__query_builder::Table::new("generate_job")
    }
}
