// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GenerateJob {
    pub id: u64,
    pub submitter: __sdk::Identity,
    pub plan_request_id: Option<u64>,
    pub tracks_json: String,
    pub status: String,
    pub zip_url: Option<String>,
    pub error: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub completed_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for GenerateJob {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GenerateJob`.
///
/// Provides typed access to columns for query building.
pub struct GenerateJobCols {
    pub id: __sdk::__query_builder::Col<GenerateJob, u64>,
    pub submitter: __sdk::__query_builder::Col<GenerateJob, __sdk::Identity>,
    pub plan_request_id: __sdk::__query_builder::Col<GenerateJob, Option<u64>>,
    pub tracks_json: __sdk::__query_builder::Col<GenerateJob, String>,
    pub status: __sdk::__query_builder::Col<GenerateJob, String>,
    pub zip_url: __sdk::__query_builder::Col<GenerateJob, Option<String>>,
    pub error: __sdk::__query_builder::Col<GenerateJob, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<GenerateJob, __sdk::Timestamp>,
    pub completed_at: __sdk::__query_builder::Col<GenerateJob, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for GenerateJob {
    type Cols = GenerateJobCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GenerateJobCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            submitter: __sdk::__query_builder::Col::new(table_name, "submitter"),
            plan_request_id: __sdk::__query_builder::Col::new(table_name, "plan_request_id"),
            tracks_json: __sdk::__query_builder::Col::new(table_name, "tracks_json"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            zip_url: __sdk::__query_builder::Col::new(table_name, "zip_url"),
            error: __sdk::__query_builder::Col::new(table_name, "error"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `GenerateJob`.
///
/// Provides typed access to indexed columns for query building.
pub struct GenerateJobIxCols {
    pub id: __sdk::__query_builder::IxCol<GenerateJob, u64>,
    pub submitter: __sdk::__query_builder::IxCol<GenerateJob, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for GenerateJob {
    type IxCols = GenerateJobIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GenerateJobIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            submitter: __sdk::__query_builder::IxCol::new(table_name, "submitter"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GenerateJob {}
