// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IssueAuthTokenArgs {
    pub token: String,
    pub email: String,
}

impl From<IssueAuthTokenArgs> for super::Reducer {
    fn from(args: IssueAuthTokenArgs) -> Self {
        Self::IssueAuthToken {
            token: args.token,
            email: args.email,
        }
    }
}

impl __sdk::InModule for IssueAuthTokenArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `issue_auth_token`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait issue_auth_token {
    /// Request that the remote module invoke the reducer `issue_auth_token` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`issue_auth_token:issue_auth_token_then`] to run a callback after the reducer completes.
    fn issue_auth_token(&self, token: String, email: String) -> __sdk::Result<()> {
        self.issue_auth_token_then(token, email, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `issue_auth_token` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn issue_auth_token_then(
        &self,
        token: String,
        email: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl issue_auth_token for super::RemoteReducers {
    fn issue_auth_token_then(
        &self,
        token: String,
        email: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(IssueAuthTokenArgs { token, email }, callback)
    }
}
