// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::log_event_type::LogEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `log_event`.
///
/// Obtain a handle from the [`LogEventTableAccess::log_event`] method on [`super::RemoteTables`],
/// like `ctx.db.log_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.log_event().on_insert(...)`.
pub struct LogEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<LogEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `log_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LogEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LogEventTableHandle`], which mediates access to the table `log_event`.
    fn log_event(&self) -> LogEventTableHandle<'_>;
}

impl LogEventTableAccess for super::RemoteTables {
    fn log_event(&self) -> LogEventTableHandle<'_> {
        LogEventTableHandle {
            imp: self.imp.get_table::<LogEvent>("log_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LogEventInsertCallbackId(__sdk::CallbackId);
pub struct LogEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LogEventTableHandle<'ctx> {
    type Row = LogEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LogEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LogEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LogEventInsertCallbackId {
        LogEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LogEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LogEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LogEventDeleteCallbackId {
        LogEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LogEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LogEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LogEventTableHandle<'ctx> {
    type UpdateCallbackId = LogEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LogEventUpdateCallbackId {
        LogEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LogEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `log_event`,
/// which allows point queries on the field of the same name
/// via the [`LogEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.log_event().id().find(...)`.
pub struct LogEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LogEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LogEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `log_event`.
    pub fn id(&self) -> LogEventIdUnique<'ctx> {
        LogEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LogEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LogEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LogEvent>("log_event");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LogEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LogEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LogEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait log_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LogEvent`.
    fn log_event(&self) -> __sdk::__query_builder::Table<LogEvent>;
}

impl log_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn log_event(&self) -> __sdk::__query_builder::Table<LogEvent> {
        __sdk::__query_builder::Table::new("log_event")
    }
}
