// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LogInterest {
    pub container: String,
    pub subscriber: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for LogInterest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LogInterest`.
///
/// Provides typed access to columns for query building.
pub struct LogInterestCols {
    pub container: __sdk::__query_builder::Col<LogInterest, String>,
    pub subscriber: __sdk::__query_builder::Col<LogInterest, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<LogInterest, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for LogInterest {
    type Cols = LogInterestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LogInterestCols {
            container: __sdk::__query_builder::Col::new(table_name, "container"),
            subscriber: __sdk::__query_builder::Col::new(table_name, "subscriber"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `LogInterest`.
///
/// Provides typed access to indexed columns for query building.
pub struct LogInterestIxCols {
    pub container: __sdk::__query_builder::IxCol<LogInterest, String>,
    pub subscriber: __sdk::__query_builder::IxCol<LogInterest, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for LogInterest {
    type IxCols = LogInterestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LogInterestIxCols {
            container: __sdk::__query_builder::IxCol::new(table_name, "container"),
            subscriber: __sdk::__query_builder::IxCol::new(table_name, "subscriber"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LogInterest {}
