// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LogEvent {
    pub id: u64,
    pub container: String,
    pub ts_micros: i64,
    pub level: String,
    pub text: String,
    pub inserted_at: __sdk::Timestamp,
}

impl __sdk::InModule for LogEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LogEvent`.
///
/// Provides typed access to columns for query building.
pub struct LogEventCols {
    pub id: __sdk::__query_builder::Col<LogEvent, u64>,
    pub container: __sdk::__query_builder::Col<LogEvent, String>,
    pub ts_micros: __sdk::__query_builder::Col<LogEvent, i64>,
    pub level: __sdk::__query_builder::Col<LogEvent, String>,
    pub text: __sdk::__query_builder::Col<LogEvent, String>,
    pub inserted_at: __sdk::__query_builder::Col<LogEvent, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for LogEvent {
    type Cols = LogEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LogEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            container: __sdk::__query_builder::Col::new(table_name, "container"),
            ts_micros: __sdk::__query_builder::Col::new(table_name, "ts_micros"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            inserted_at: __sdk::__query_builder::Col::new(table_name, "inserted_at"),
        }
    }
}

/// Indexed column accessor struct for the table `LogEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct LogEventIxCols {
    pub container: __sdk::__query_builder::IxCol<LogEvent, String>,
    pub id: __sdk::__query_builder::IxCol<LogEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for LogEvent {
    type IxCols = LogEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LogEventIxCols {
            container: __sdk::__query_builder::IxCol::new(table_name, "container"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LogEvent {}
