// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod add_log_interest_reducer;
pub mod app_config_secret_type;
pub mod app_config_table;
pub mod app_config_type;
pub mod append_log_event_reducer;
pub mod auth_token_type;
pub mod comment_table;
pub mod comment_type;
pub mod consume_auth_token_reducer;
pub mod container_status_table;
pub mod container_status_type;
pub mod delete_comment_reducer;
pub mod delete_project_reducer;
pub mod generate_job_table;
pub mod generate_job_type;
pub mod heartbeat_reducer;
pub mod issue_auth_token_reducer;
pub mod last_test_token_type;
pub mod log_event_table;
pub mod log_event_type;
pub mod log_interest_type;
pub mod mark_email_failed_reducer;
pub mod mark_email_sent_reducer;
pub mod mint_test_token_reducer;
pub mod moderation_event_table;
pub mod moderation_event_type;
pub mod pending_email_type;
pub mod plan_request_table;
pub mod plan_request_type;
pub mod presence_table;
pub mod presence_type;
pub mod project_table;
pub mod project_type;
pub mod prune_log_events_schedule_type;
pub mod register_user_reducer;
pub mod remove_log_interest_reducer;
pub mod request_generate_reducer;
pub mod request_magic_link_reducer;
pub mod request_plan_reducer;
pub mod set_app_config_reducer;
pub mod set_comment_status_reducer;
pub mod set_comment_status_with_reason_reducer;
pub mod set_e_2_e_test_secret_reducer;
pub mod set_generate_done_reducer;
pub mod set_generate_failed_reducer;
pub mod set_plan_failed_reducer;
pub mod set_plan_fallback_reducer;
pub mod set_plan_reducer;
pub mod submit_user_comment_reducer;
pub mod system_metrics_table;
pub mod system_metrics_type;
pub mod upsert_container_status_reducer;
pub mod upsert_project_reducer;
pub mod upsert_system_metrics_reducer;
pub mod user_table;
pub mod user_type;
pub mod verify_token_reducer;

pub use add_log_interest_reducer::add_log_interest;
pub use app_config_secret_type::AppConfigSecret;
pub use app_config_table::*;
pub use app_config_type::AppConfig;
pub use append_log_event_reducer::append_log_event;
pub use auth_token_type::AuthToken;
pub use comment_table::*;
pub use comment_type::Comment;
pub use consume_auth_token_reducer::consume_auth_token;
pub use container_status_table::*;
pub use container_status_type::ContainerStatus;
pub use delete_comment_reducer::delete_comment;
pub use delete_project_reducer::delete_project;
pub use generate_job_table::*;
pub use generate_job_type::GenerateJob;
pub use heartbeat_reducer::heartbeat;
pub use issue_auth_token_reducer::issue_auth_token;
pub use last_test_token_type::LastTestToken;
pub use log_event_table::*;
pub use log_event_type::LogEvent;
pub use log_interest_type::LogInterest;
pub use mark_email_failed_reducer::mark_email_failed;
pub use mark_email_sent_reducer::mark_email_sent;
pub use mint_test_token_reducer::mint_test_token;
pub use moderation_event_table::*;
pub use moderation_event_type::ModerationEvent;
pub use pending_email_type::PendingEmail;
pub use plan_request_table::*;
pub use plan_request_type::PlanRequest;
pub use presence_table::*;
pub use presence_type::Presence;
pub use project_table::*;
pub use project_type::Project;
pub use prune_log_events_schedule_type::PruneLogEventsSchedule;
pub use register_user_reducer::register_user;
pub use remove_log_interest_reducer::remove_log_interest;
pub use request_generate_reducer::request_generate;
pub use request_magic_link_reducer::request_magic_link;
pub use request_plan_reducer::request_plan;
pub use set_app_config_reducer::set_app_config;
pub use set_comment_status_reducer::set_comment_status;
pub use set_comment_status_with_reason_reducer::set_comment_status_with_reason;
pub use set_e_2_e_test_secret_reducer::set_e_2_e_test_secret;
pub use set_generate_done_reducer::set_generate_done;
pub use set_generate_failed_reducer::set_generate_failed;
pub use set_plan_failed_reducer::set_plan_failed;
pub use set_plan_fallback_reducer::set_plan_fallback;
pub use set_plan_reducer::set_plan;
pub use submit_user_comment_reducer::submit_user_comment;
pub use system_metrics_table::*;
pub use system_metrics_type::SystemMetrics;
pub use upsert_container_status_reducer::upsert_container_status;
pub use upsert_project_reducer::upsert_project;
pub use upsert_system_metrics_reducer::upsert_system_metrics;
pub use user_table::*;
pub use user_type::User;
pub use verify_token_reducer::verify_token;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AddLogInterest {
        container: String,
    },
    AppendLogEvent {
        container: String,
        ts_micros: i64,
        level: String,
        text: String,
    },
    ConsumeAuthToken {
        token: String,
    },
    DeleteComment {
        id: u64,
    },
    DeleteProject {
        slug: String,
    },
    Heartbeat,
    IssueAuthToken {
        token: String,
        email: String,
    },
    MarkEmailFailed {
        id: u64,
        error: String,
    },
    MarkEmailSent {
        id: u64,
        provider_msg_id: String,
    },
    MintTestToken {
        email: String,
        secret: String,
    },
    RegisterUser {
        user_identity: __sdk::Identity,
        email: String,
        display_name: String,
    },
    RemoveLogInterest {
        container: String,
    },
    RequestGenerate {
        plan_request_id: Option<u64>,
        tracks_json: String,
    },
    RequestMagicLink {
        email: String,
        app: String,
        prev_identity_hex: Option<String>,
        callback_url: String,
    },
    RequestPlan {
        description: String,
        count: u32,
    },
    SetAppConfig {
        notes_callback: String,
        typewars_callback: String,
        admin_callback: String,
        deck_origin: String,
    },
    SetCommentStatus {
        id: u64,
        status: String,
    },
    SetCommentStatusWithReason {
        id: u64,
        status: String,
        reason: String,
    },
    SetE2ETestSecret {
        secret: Option<String>,
    },
    SetGenerateDone {
        job_id: u64,
        zip_url: String,
    },
    SetGenerateFailed {
        job_id: u64,
        error: String,
    },
    SetPlan {
        request_id: u64,
        tracks_json: String,
    },
    SetPlanFailed {
        request_id: u64,
        error: String,
    },
    SetPlanFallback {
        request_id: u64,
    },
    SubmitUserComment {
        post_slug: String,
        body: String,
    },
    UpsertContainerStatus {
        name: String,
        status: String,
        image: String,
        uptime_s: u64,
        mem_used_mb: u32,
        mem_limit_mb: u32,
        restart_count: u32,
    },
    UpsertProject {
        slug: String,
        title: String,
        blurb: String,
        status: String,
        tags: Vec<String>,
        url: String,
    },
    UpsertSystemMetrics {
        cpu_pct: f32,
        cores: u32,
        mem_used_gb: f32,
        mem_total_gb: f32,
        mem_pct: f32,
        swap_used_mb: u32,
        swap_total_mb: u32,
        disk_used_gb: u32,
        disk_total_gb: u32,
        disk_pct: f32,
        net_tx_bytes: u64,
        net_rx_bytes: u64,
        uptime_s: u64,
        gpu_pct: Option<u32>,
        gpu_vram_used_mb: Option<u32>,
        gpu_vram_total_mb: Option<u32>,
        gpu_temp_c: Option<u32>,
        gpu_model: Option<String>,
    },
    VerifyToken {
        token: String,
        display_name: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AddLogInterest { .. } => "add_log_interest",
            Reducer::AppendLogEvent { .. } => "append_log_event",
            Reducer::ConsumeAuthToken { .. } => "consume_auth_token",
            Reducer::DeleteComment { .. } => "delete_comment",
            Reducer::DeleteProject { .. } => "delete_project",
            Reducer::Heartbeat => "heartbeat",
            Reducer::IssueAuthToken { .. } => "issue_auth_token",
            Reducer::MarkEmailFailed { .. } => "mark_email_failed",
            Reducer::MarkEmailSent { .. } => "mark_email_sent",
            Reducer::MintTestToken { .. } => "mint_test_token",
            Reducer::RegisterUser { .. } => "register_user",
            Reducer::RemoveLogInterest { .. } => "remove_log_interest",
            Reducer::RequestGenerate { .. } => "request_generate",
            Reducer::RequestMagicLink { .. } => "request_magic_link",
            Reducer::RequestPlan { .. } => "request_plan",
            Reducer::SetAppConfig { .. } => "set_app_config",
            Reducer::SetCommentStatus { .. } => "set_comment_status",
            Reducer::SetCommentStatusWithReason { .. } => "set_comment_status_with_reason",
            Reducer::SetE2ETestSecret { .. } => "set_e_2_e_test_secret",
            Reducer::SetGenerateDone { .. } => "set_generate_done",
            Reducer::SetGenerateFailed { .. } => "set_generate_failed",
            Reducer::SetPlan { .. } => "set_plan",
            Reducer::SetPlanFailed { .. } => "set_plan_failed",
            Reducer::SetPlanFallback { .. } => "set_plan_fallback",
            Reducer::SubmitUserComment { .. } => "submit_user_comment",
            Reducer::UpsertContainerStatus { .. } => "upsert_container_status",
            Reducer::UpsertProject { .. } => "upsert_project",
            Reducer::UpsertSystemMetrics { .. } => "upsert_system_metrics",
            Reducer::VerifyToken { .. } => "verify_token",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AddLogInterest { container } => {
                __sats::bsatn::to_vec(&add_log_interest_reducer::AddLogInterestArgs {
                    container: container.clone(),
                })
            }
            Reducer::AppendLogEvent {
                container,
                ts_micros,
                level,
                text,
            } => __sats::bsatn::to_vec(&append_log_event_reducer::AppendLogEventArgs {
                container: container.clone(),
                ts_micros: ts_micros.clone(),
                level: level.clone(),
                text: text.clone(),
            }),
            Reducer::ConsumeAuthToken { token } => {
                __sats::bsatn::to_vec(&consume_auth_token_reducer::ConsumeAuthTokenArgs {
                    token: token.clone(),
                })
            }
            Reducer::DeleteComment { id } => {
                __sats::bsatn::to_vec(&delete_comment_reducer::DeleteCommentArgs { id: id.clone() })
            }
            Reducer::DeleteProject { slug } => {
                __sats::bsatn::to_vec(&delete_project_reducer::DeleteProjectArgs {
                    slug: slug.clone(),
                })
            }
            Reducer::Heartbeat => __sats::bsatn::to_vec(&heartbeat_reducer::HeartbeatArgs {}),
            Reducer::IssueAuthToken { token, email } => {
                __sats::bsatn::to_vec(&issue_auth_token_reducer::IssueAuthTokenArgs {
                    token: token.clone(),
                    email: email.clone(),
                })
            }
            Reducer::MarkEmailFailed { id, error } => {
                __sats::bsatn::to_vec(&mark_email_failed_reducer::MarkEmailFailedArgs {
                    id: id.clone(),
                    error: error.clone(),
                })
            }
            Reducer::MarkEmailSent {
                id,
                provider_msg_id,
            } => __sats::bsatn::to_vec(&mark_email_sent_reducer::MarkEmailSentArgs {
                id: id.clone(),
                provider_msg_id: provider_msg_id.clone(),
            }),
            Reducer::MintTestToken { email, secret } => {
                __sats::bsatn::to_vec(&mint_test_token_reducer::MintTestTokenArgs {
                    email: email.clone(),
                    secret: secret.clone(),
                })
            }
            Reducer::RegisterUser {
                user_identity,
                email,
                display_name,
            } => __sats::bsatn::to_vec(&register_user_reducer::RegisterUserArgs {
                user_identity: user_identity.clone(),
                email: email.clone(),
                display_name: display_name.clone(),
            }),
            Reducer::RemoveLogInterest { container } => {
                __sats::bsatn::to_vec(&remove_log_interest_reducer::RemoveLogInterestArgs {
                    container: container.clone(),
                })
            }
            Reducer::RequestGenerate {
                plan_request_id,
                tracks_json,
            } => __sats::bsatn::to_vec(&request_generate_reducer::RequestGenerateArgs {
                plan_request_id: plan_request_id.clone(),
                tracks_json: tracks_json.clone(),
            }),
            Reducer::RequestMagicLink {
                email,
                app,
                prev_identity_hex,
                callback_url,
            } => __sats::bsatn::to_vec(&request_magic_link_reducer::RequestMagicLinkArgs {
                email: email.clone(),
                app: app.clone(),
                prev_identity_hex: prev_identity_hex.clone(),
                callback_url: callback_url.clone(),
            }),
            Reducer::RequestPlan { description, count } => {
                __sats::bsatn::to_vec(&request_plan_reducer::RequestPlanArgs {
                    description: description.clone(),
                    count: count.clone(),
                })
            }
            Reducer::SetAppConfig {
                notes_callback,
                typewars_callback,
                admin_callback,
                deck_origin,
            } => __sats::bsatn::to_vec(&set_app_config_reducer::SetAppConfigArgs {
                notes_callback: notes_callback.clone(),
                typewars_callback: typewars_callback.clone(),
                admin_callback: admin_callback.clone(),
                deck_origin: deck_origin.clone(),
            }),
            Reducer::SetCommentStatus { id, status } => {
                __sats::bsatn::to_vec(&set_comment_status_reducer::SetCommentStatusArgs {
                    id: id.clone(),
                    status: status.clone(),
                })
            }
            Reducer::SetCommentStatusWithReason { id, status, reason } => __sats::bsatn::to_vec(
                &set_comment_status_with_reason_reducer::SetCommentStatusWithReasonArgs {
                    id: id.clone(),
                    status: status.clone(),
                    reason: reason.clone(),
                },
            ),
            Reducer::SetE2ETestSecret { secret } => {
                __sats::bsatn::to_vec(&set_e_2_e_test_secret_reducer::SetE2ETestSecretArgs {
                    secret: secret.clone(),
                })
            }
            Reducer::SetGenerateDone { job_id, zip_url } => {
                __sats::bsatn::to_vec(&set_generate_done_reducer::SetGenerateDoneArgs {
                    job_id: job_id.clone(),
                    zip_url: zip_url.clone(),
                })
            }
            Reducer::SetGenerateFailed { job_id, error } => {
                __sats::bsatn::to_vec(&set_generate_failed_reducer::SetGenerateFailedArgs {
                    job_id: job_id.clone(),
                    error: error.clone(),
                })
            }
            Reducer::SetPlan {
                request_id,
                tracks_json,
            } => __sats::bsatn::to_vec(&set_plan_reducer::SetPlanArgs {
                request_id: request_id.clone(),
                tracks_json: tracks_json.clone(),
            }),
            Reducer::SetPlanFailed { request_id, error } => {
                __sats::bsatn::to_vec(&set_plan_failed_reducer::SetPlanFailedArgs {
                    request_id: request_id.clone(),
                    error: error.clone(),
                })
            }
            Reducer::SetPlanFallback { request_id } => {
                __sats::bsatn::to_vec(&set_plan_fallback_reducer::SetPlanFallbackArgs {
                    request_id: request_id.clone(),
                })
            }
            Reducer::SubmitUserComment { post_slug, body } => {
                __sats::bsatn::to_vec(&submit_user_comment_reducer::SubmitUserCommentArgs {
                    post_slug: post_slug.clone(),
                    body: body.clone(),
                })
            }
            Reducer::UpsertContainerStatus {
                name,
                status,
                image,
                uptime_s,
                mem_used_mb,
                mem_limit_mb,
                restart_count,
            } => __sats::bsatn::to_vec(
                &upsert_container_status_reducer::UpsertContainerStatusArgs {
                    name: name.clone(),
                    status: status.clone(),
                    image: image.clone(),
                    uptime_s: uptime_s.clone(),
                    mem_used_mb: mem_used_mb.clone(),
                    mem_limit_mb: mem_limit_mb.clone(),
                    restart_count: restart_count.clone(),
                },
            ),
            Reducer::UpsertProject {
                slug,
                title,
                blurb,
                status,
                tags,
                url,
            } => __sats::bsatn::to_vec(&upsert_project_reducer::UpsertProjectArgs {
                slug: slug.clone(),
                title: title.clone(),
                blurb: blurb.clone(),
                status: status.clone(),
                tags: tags.clone(),
                url: url.clone(),
            }),
            Reducer::UpsertSystemMetrics {
                cpu_pct,
                cores,
                mem_used_gb,
                mem_total_gb,
                mem_pct,
                swap_used_mb,
                swap_total_mb,
                disk_used_gb,
                disk_total_gb,
                disk_pct,
                net_tx_bytes,
                net_rx_bytes,
                uptime_s,
                gpu_pct,
                gpu_vram_used_mb,
                gpu_vram_total_mb,
                gpu_temp_c,
                gpu_model,
            } => __sats::bsatn::to_vec(&upsert_system_metrics_reducer::UpsertSystemMetricsArgs {
                cpu_pct: cpu_pct.clone(),
                cores: cores.clone(),
                mem_used_gb: mem_used_gb.clone(),
                mem_total_gb: mem_total_gb.clone(),
                mem_pct: mem_pct.clone(),
                swap_used_mb: swap_used_mb.clone(),
                swap_total_mb: swap_total_mb.clone(),
                disk_used_gb: disk_used_gb.clone(),
                disk_total_gb: disk_total_gb.clone(),
                disk_pct: disk_pct.clone(),
                net_tx_bytes: net_tx_bytes.clone(),
                net_rx_bytes: net_rx_bytes.clone(),
                uptime_s: uptime_s.clone(),
                gpu_pct: gpu_pct.clone(),
                gpu_vram_used_mb: gpu_vram_used_mb.clone(),
                gpu_vram_total_mb: gpu_vram_total_mb.clone(),
                gpu_temp_c: gpu_temp_c.clone(),
                gpu_model: gpu_model.clone(),
            }),
            Reducer::VerifyToken {
                token,
                display_name,
            } => __sats::bsatn::to_vec(&verify_token_reducer::VerifyTokenArgs {
                token: token.clone(),
                display_name: display_name.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    app_config: __sdk::TableUpdate<AppConfig>,
    comment: __sdk::TableUpdate<Comment>,
    container_status: __sdk::TableUpdate<ContainerStatus>,
    generate_job: __sdk::TableUpdate<GenerateJob>,
    log_event: __sdk::TableUpdate<LogEvent>,
    moderation_event: __sdk::TableUpdate<ModerationEvent>,
    plan_request: __sdk::TableUpdate<PlanRequest>,
    presence: __sdk::TableUpdate<Presence>,
    project: __sdk::TableUpdate<Project>,
    system_metrics: __sdk::TableUpdate<SystemMetrics>,
    user: __sdk::TableUpdate<User>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "app_config" => db_update
                    .app_config
                    .append(app_config_table::parse_table_update(table_update)?),
                "comment" => db_update
                    .comment
                    .append(comment_table::parse_table_update(table_update)?),
                "container_status" => db_update
                    .container_status
                    .append(container_status_table::parse_table_update(table_update)?),
                "generate_job" => db_update
                    .generate_job
                    .append(generate_job_table::parse_table_update(table_update)?),
                "log_event" => db_update
                    .log_event
                    .append(log_event_table::parse_table_update(table_update)?),
                "moderation_event" => db_update
                    .moderation_event
                    .append(moderation_event_table::parse_table_update(table_update)?),
                "plan_request" => db_update
                    .plan_request
                    .append(plan_request_table::parse_table_update(table_update)?),
                "presence" => db_update
                    .presence
                    .append(presence_table::parse_table_update(table_update)?),
                "project" => db_update
                    .project
                    .append(project_table::parse_table_update(table_update)?),
                "system_metrics" => db_update
                    .system_metrics
                    .append(system_metrics_table::parse_table_update(table_update)?),
                "user" => db_update
                    .user
                    .append(user_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.app_config = cache
            .apply_diff_to_table::<AppConfig>("app_config", &self.app_config)
            .with_updates_by_pk(|row| &row.id);
        diff.comment = cache
            .apply_diff_to_table::<Comment>("comment", &self.comment)
            .with_updates_by_pk(|row| &row.id);
        diff.container_status = cache
            .apply_diff_to_table::<ContainerStatus>("container_status", &self.container_status)
            .with_updates_by_pk(|row| &row.name);
        diff.generate_job = cache
            .apply_diff_to_table::<GenerateJob>("generate_job", &self.generate_job)
            .with_updates_by_pk(|row| &row.id);
        diff.log_event = cache
            .apply_diff_to_table::<LogEvent>("log_event", &self.log_event)
            .with_updates_by_pk(|row| &row.id);
        diff.moderation_event = cache
            .apply_diff_to_table::<ModerationEvent>("moderation_event", &self.moderation_event)
            .with_updates_by_pk(|row| &row.id);
        diff.plan_request = cache
            .apply_diff_to_table::<PlanRequest>("plan_request", &self.plan_request)
            .with_updates_by_pk(|row| &row.id);
        diff.presence = cache
            .apply_diff_to_table::<Presence>("presence", &self.presence)
            .with_updates_by_pk(|row| &row.identity);
        diff.project = cache
            .apply_diff_to_table::<Project>("project", &self.project)
            .with_updates_by_pk(|row| &row.slug);
        diff.system_metrics = cache
            .apply_diff_to_table::<SystemMetrics>("system_metrics", &self.system_metrics)
            .with_updates_by_pk(|row| &row.id);
        diff.user = cache
            .apply_diff_to_table::<User>("user", &self.user)
            .with_updates_by_pk(|row| &row.identity);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "app_config" => db_update
                    .app_config
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "comment" => db_update
                    .comment
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "container_status" => db_update
                    .container_status
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "generate_job" => db_update
                    .generate_job
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "log_event" => db_update
                    .log_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "moderation_event" => db_update
                    .moderation_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "plan_request" => db_update
                    .plan_request
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "presence" => db_update
                    .presence
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "project" => db_update
                    .project
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "system_metrics" => db_update
                    .system_metrics
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user" => db_update
                    .user
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "app_config" => db_update
                    .app_config
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "comment" => db_update
                    .comment
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "container_status" => db_update
                    .container_status
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "generate_job" => db_update
                    .generate_job
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "log_event" => db_update
                    .log_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "moderation_event" => db_update
                    .moderation_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "plan_request" => db_update
                    .plan_request
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "presence" => db_update
                    .presence
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "project" => db_update
                    .project
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "system_metrics" => db_update
                    .system_metrics
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user" => db_update
                    .user
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    app_config: __sdk::TableAppliedDiff<'r, AppConfig>,
    comment: __sdk::TableAppliedDiff<'r, Comment>,
    container_status: __sdk::TableAppliedDiff<'r, ContainerStatus>,
    generate_job: __sdk::TableAppliedDiff<'r, GenerateJob>,
    log_event: __sdk::TableAppliedDiff<'r, LogEvent>,
    moderation_event: __sdk::TableAppliedDiff<'r, ModerationEvent>,
    plan_request: __sdk::TableAppliedDiff<'r, PlanRequest>,
    presence: __sdk::TableAppliedDiff<'r, Presence>,
    project: __sdk::TableAppliedDiff<'r, Project>,
    system_metrics: __sdk::TableAppliedDiff<'r, SystemMetrics>,
    user: __sdk::TableAppliedDiff<'r, User>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<AppConfig>("app_config", &self.app_config, event);
        callbacks.invoke_table_row_callbacks::<Comment>("comment", &self.comment, event);
        callbacks.invoke_table_row_callbacks::<ContainerStatus>(
            "container_status",
            &self.container_status,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GenerateJob>(
            "generate_job",
            &self.generate_job,
            event,
        );
        callbacks.invoke_table_row_callbacks::<LogEvent>("log_event", &self.log_event, event);
        callbacks.invoke_table_row_callbacks::<ModerationEvent>(
            "moderation_event",
            &self.moderation_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlanRequest>(
            "plan_request",
            &self.plan_request,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Presence>("presence", &self.presence, event);
        callbacks.invoke_table_row_callbacks::<Project>("project", &self.project, event);
        callbacks.invoke_table_row_callbacks::<SystemMetrics>(
            "system_metrics",
            &self.system_metrics,
            event,
        );
        callbacks.invoke_table_row_callbacks::<User>("user", &self.user, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        app_config_table::register_table(client_cache);
        comment_table::register_table(client_cache);
        container_status_table::register_table(client_cache);
        generate_job_table::register_table(client_cache);
        log_event_table::register_table(client_cache);
        moderation_event_table::register_table(client_cache);
        plan_request_table::register_table(client_cache);
        presence_table::register_table(client_cache);
        project_table::register_table(client_cache);
        system_metrics_table::register_table(client_cache);
        user_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "app_config",
        "comment",
        "container_status",
        "generate_job",
        "log_event",
        "moderation_event",
        "plan_request",
        "presence",
        "project",
        "system_metrics",
        "user",
    ];
}
