// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::moderation_event_type::ModerationEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `moderation_event`.
///
/// Obtain a handle from the [`ModerationEventTableAccess::moderation_event`] method on [`super::RemoteTables`],
/// like `ctx.db.moderation_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.moderation_event().on_insert(...)`.
pub struct ModerationEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<ModerationEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `moderation_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ModerationEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ModerationEventTableHandle`], which mediates access to the table `moderation_event`.
    fn moderation_event(&self) -> ModerationEventTableHandle<'_>;
}

impl ModerationEventTableAccess for super::RemoteTables {
    fn moderation_event(&self) -> ModerationEventTableHandle<'_> {
        ModerationEventTableHandle {
            imp: self.imp.get_table::<ModerationEvent>("moderation_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ModerationEventInsertCallbackId(__sdk::CallbackId);
pub struct ModerationEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ModerationEventTableHandle<'ctx> {
    type Row = ModerationEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ModerationEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ModerationEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ModerationEventInsertCallbackId {
        ModerationEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ModerationEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ModerationEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ModerationEventDeleteCallbackId {
        ModerationEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ModerationEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ModerationEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ModerationEventTableHandle<'ctx> {
    type UpdateCallbackId = ModerationEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ModerationEventUpdateCallbackId {
        ModerationEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ModerationEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `moderation_event`,
/// which allows point queries on the field of the same name
/// via the [`ModerationEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.moderation_event().id().find(...)`.
pub struct ModerationEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ModerationEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ModerationEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `moderation_event`.
    pub fn id(&self) -> ModerationEventIdUnique<'ctx> {
        ModerationEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ModerationEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ModerationEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ModerationEvent>("moderation_event");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ModerationEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ModerationEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ModerationEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait moderation_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ModerationEvent`.
    fn moderation_event(&self) -> __sdk::__query_builder::Table<ModerationEvent>;
}

impl moderation_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn moderation_event(&self) -> __sdk::__query_builder::Table<ModerationEvent> {
        __sdk::__query_builder::Table::new("moderation_event")
    }
}
