// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ModerationEvent {
    pub id: u64,
    pub comment_id: u64,
    pub status: String,
    pub reason: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for ModerationEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ModerationEvent`.
///
/// Provides typed access to columns for query building.
pub struct ModerationEventCols {
    pub id: __sdk::__query_builder::Col<ModerationEvent, u64>,
    pub comment_id: __sdk::__query_builder::Col<ModerationEvent, u64>,
    pub status: __sdk::__query_builder::Col<ModerationEvent, String>,
    pub reason: __sdk::__query_builder::Col<ModerationEvent, String>,
    pub created_at: __sdk::__query_builder::Col<ModerationEvent, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ModerationEvent {
    type Cols = ModerationEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ModerationEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            comment_id: __sdk::__query_builder::Col::new(table_name, "comment_id"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ModerationEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct ModerationEventIxCols {
    pub comment_id: __sdk::__query_builder::IxCol<ModerationEvent, u64>,
    pub id: __sdk::__query_builder::IxCol<ModerationEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for ModerationEvent {
    type IxCols = ModerationEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ModerationEventIxCols {
            comment_id: __sdk::__query_builder::IxCol::new(table_name, "comment_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ModerationEvent {}
