// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PendingEmail {
    pub id: u64,
    pub to_email: String,
    pub subject: String,
    pub body_html: String,
    pub body_text: String,
    pub created_at: __sdk::Timestamp,
    pub status: String,
    pub provider_msg_id: Option<String>,
    pub error: Option<String>,
}

impl __sdk::InModule for PendingEmail {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PendingEmail`.
///
/// Provides typed access to columns for query building.
pub struct PendingEmailCols {
    pub id: __sdk::__query_builder::Col<PendingEmail, u64>,
    pub to_email: __sdk::__query_builder::Col<PendingEmail, String>,
    pub subject: __sdk::__query_builder::Col<PendingEmail, String>,
    pub body_html: __sdk::__query_builder::Col<PendingEmail, String>,
    pub body_text: __sdk::__query_builder::Col<PendingEmail, String>,
    pub created_at: __sdk::__query_builder::Col<PendingEmail, __sdk::Timestamp>,
    pub status: __sdk::__query_builder::Col<PendingEmail, String>,
    pub provider_msg_id: __sdk::__query_builder::Col<PendingEmail, Option<String>>,
    pub error: __sdk::__query_builder::Col<PendingEmail, Option<String>>,
}

impl __sdk::__query_builder::HasCols for PendingEmail {
    type Cols = PendingEmailCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PendingEmailCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            to_email: __sdk::__query_builder::Col::new(table_name, "to_email"),
            subject: __sdk::__query_builder::Col::new(table_name, "subject"),
            body_html: __sdk::__query_builder::Col::new(table_name, "body_html"),
            body_text: __sdk::__query_builder::Col::new(table_name, "body_text"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            provider_msg_id: __sdk::__query_builder::Col::new(table_name, "provider_msg_id"),
            error: __sdk::__query_builder::Col::new(table_name, "error"),
        }
    }
}

/// Indexed column accessor struct for the table `PendingEmail`.
///
/// Provides typed access to indexed columns for query building.
pub struct PendingEmailIxCols {
    pub id: __sdk::__query_builder::IxCol<PendingEmail, u64>,
}

impl __sdk::__query_builder::HasIxCols for PendingEmail {
    type IxCols = PendingEmailIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PendingEmailIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PendingEmail {}
