// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::plan_request_type::PlanRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `plan_request`.
///
/// Obtain a handle from the [`PlanRequestTableAccess::plan_request`] method on [`super::RemoteTables`],
/// like `ctx.db.plan_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.plan_request().on_insert(...)`.
pub struct PlanRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlanRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `plan_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlanRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlanRequestTableHandle`], which mediates access to the table `plan_request`.
    fn plan_request(&self) -> PlanRequestTableHandle<'_>;
}

impl PlanRequestTableAccess for super::RemoteTables {
    fn plan_request(&self) -> PlanRequestTableHandle<'_> {
        PlanRequestTableHandle {
            imp: self.imp.get_table::<PlanRequest>("plan_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlanRequestInsertCallbackId(__sdk::CallbackId);
pub struct PlanRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlanRequestTableHandle<'ctx> {
    type Row = PlanRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlanRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlanRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlanRequestInsertCallbackId {
        PlanRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlanRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlanRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlanRequestDeleteCallbackId {
        PlanRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlanRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlanRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlanRequestTableHandle<'ctx> {
    type UpdateCallbackId = PlanRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlanRequestUpdateCallbackId {
        PlanRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlanRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `plan_request`,
/// which allows point queries on the field of the same name
/// via the [`PlanRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.plan_request().id().find(...)`.
pub struct PlanRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlanRequest, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlanRequestTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `plan_request`.
    pub fn id(&self) -> PlanRequestIdUnique<'ctx> {
        PlanRequestIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlanRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlanRequest> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlanRequest>("plan_request");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlanRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlanRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlanRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait plan_requestQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlanRequest`.
    fn plan_request(&self) -> __sdk::__query_builder::Table<PlanRequest>;
}

impl plan_requestQueryTableAccess for __sdk::QueryTableAccessor {
    fn plan_request(&self) -> __sdk::__query_builder::Table<PlanRequest> {
        __sdk::__query_builder::Table::new("plan_request")
    }
}
