// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlanRequest {
    pub id: u64,
    pub submitter: __sdk::Identity,
    pub description: String,
    pub count: u32,
    pub status: String,
    pub tracks_json: Option<String>,
    pub error: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub completed_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for PlanRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlanRequest`.
///
/// Provides typed access to columns for query building.
pub struct PlanRequestCols {
    pub id: __sdk::__query_builder::Col<PlanRequest, u64>,
    pub submitter: __sdk::__query_builder::Col<PlanRequest, __sdk::Identity>,
    pub description: __sdk::__query_builder::Col<PlanRequest, String>,
    pub count: __sdk::__query_builder::Col<PlanRequest, u32>,
    pub status: __sdk::__query_builder::Col<PlanRequest, String>,
    pub tracks_json: __sdk::__query_builder::Col<PlanRequest, Option<String>>,
    pub error: __sdk::__query_builder::Col<PlanRequest, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<PlanRequest, __sdk::Timestamp>,
    pub completed_at: __sdk::__query_builder::Col<PlanRequest, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for PlanRequest {
    type Cols = PlanRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlanRequestCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            submitter: __sdk::__query_builder::Col::new(table_name, "submitter"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            tracks_json: __sdk::__query_builder::Col::new(table_name, "tracks_json"),
            error: __sdk::__query_builder::Col::new(table_name, "error"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PlanRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlanRequestIxCols {
    pub id: __sdk::__query_builder::IxCol<PlanRequest, u64>,
    pub submitter: __sdk::__query_builder::IxCol<PlanRequest, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for PlanRequest {
    type IxCols = PlanRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlanRequestIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            submitter: __sdk::__query_builder::IxCol::new(table_name, "submitter"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlanRequest {}
