// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::presence_type::Presence;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `presence`.
///
/// Obtain a handle from the [`PresenceTableAccess::presence`] method on [`super::RemoteTables`],
/// like `ctx.db.presence()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.presence().on_insert(...)`.
pub struct PresenceTableHandle<'ctx> {
    imp: __sdk::TableHandle<Presence>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `presence`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PresenceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PresenceTableHandle`], which mediates access to the table `presence`.
    fn presence(&self) -> PresenceTableHandle<'_>;
}

impl PresenceTableAccess for super::RemoteTables {
    fn presence(&self) -> PresenceTableHandle<'_> {
        PresenceTableHandle {
            imp: self.imp.get_table::<Presence>("presence"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PresenceInsertCallbackId(__sdk::CallbackId);
pub struct PresenceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PresenceTableHandle<'ctx> {
    type Row = Presence;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Presence> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PresenceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PresenceInsertCallbackId {
        PresenceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PresenceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PresenceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PresenceDeleteCallbackId {
        PresenceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PresenceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PresenceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PresenceTableHandle<'ctx> {
    type UpdateCallbackId = PresenceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PresenceUpdateCallbackId {
        PresenceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PresenceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `presence`,
/// which allows point queries on the field of the same name
/// via the [`PresenceIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.presence().identity().find(...)`.
pub struct PresenceIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Presence, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PresenceTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `presence`.
    pub fn identity(&self) -> PresenceIdentityUnique<'ctx> {
        PresenceIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PresenceIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Presence> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Presence>("presence");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Presence>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Presence>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Presence`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait presenceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Presence`.
    fn presence(&self) -> __sdk::__query_builder::Table<Presence>;
}

impl presenceQueryTableAccess for __sdk::QueryTableAccessor {
    fn presence(&self) -> __sdk::__query_builder::Table<Presence> {
        __sdk::__query_builder::Table::new("presence")
    }
}
