// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Presence {
    pub identity: __sdk::Identity,
    pub joined_at: __sdk::Timestamp,
    pub last_seen: __sdk::Timestamp,
}

impl __sdk::InModule for Presence {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Presence`.
///
/// Provides typed access to columns for query building.
pub struct PresenceCols {
    pub identity: __sdk::__query_builder::Col<Presence, __sdk::Identity>,
    pub joined_at: __sdk::__query_builder::Col<Presence, __sdk::Timestamp>,
    pub last_seen: __sdk::__query_builder::Col<Presence, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Presence {
    type Cols = PresenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PresenceCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            joined_at: __sdk::__query_builder::Col::new(table_name, "joined_at"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
        }
    }
}

/// Indexed column accessor struct for the table `Presence`.
///
/// Provides typed access to indexed columns for query building.
pub struct PresenceIxCols {
    pub identity: __sdk::__query_builder::IxCol<Presence, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Presence {
    type IxCols = PresenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PresenceIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Presence {}
