// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::project_type::Project;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `project`.
///
/// Obtain a handle from the [`ProjectTableAccess::project`] method on [`super::RemoteTables`],
/// like `ctx.db.project()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.project().on_insert(...)`.
pub struct ProjectTableHandle<'ctx> {
    imp: __sdk::TableHandle<Project>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `project`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ProjectTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ProjectTableHandle`], which mediates access to the table `project`.
    fn project(&self) -> ProjectTableHandle<'_>;
}

impl ProjectTableAccess for super::RemoteTables {
    fn project(&self) -> ProjectTableHandle<'_> {
        ProjectTableHandle {
            imp: self.imp.get_table::<Project>("project"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ProjectInsertCallbackId(__sdk::CallbackId);
pub struct ProjectDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ProjectTableHandle<'ctx> {
    type Row = Project;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Project> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ProjectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ProjectInsertCallbackId {
        ProjectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ProjectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ProjectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ProjectDeleteCallbackId {
        ProjectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ProjectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ProjectUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ProjectTableHandle<'ctx> {
    type UpdateCallbackId = ProjectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ProjectUpdateCallbackId {
        ProjectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ProjectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `slug` unique index on the table `project`,
/// which allows point queries on the field of the same name
/// via the [`ProjectSlugUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.project().slug().find(...)`.
pub struct ProjectSlugUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Project, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ProjectTableHandle<'ctx> {
    /// Get a handle on the `slug` unique index on the table `project`.
    pub fn slug(&self) -> ProjectSlugUnique<'ctx> {
        ProjectSlugUnique {
            imp: self.imp.get_unique_constraint::<String>("slug"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ProjectSlugUnique<'ctx> {
    /// Find the subscribed row whose `slug` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Project> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Project>("project");
    _table.add_unique_constraint::<String>("slug", |row| &row.slug);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Project>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Project>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Project`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait projectQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Project`.
    fn project(&self) -> __sdk::__query_builder::Table<Project>;
}

impl projectQueryTableAccess for __sdk::QueryTableAccessor {
    fn project(&self) -> __sdk::__query_builder::Table<Project> {
        __sdk::__query_builder::Table::new("project")
    }
}
