// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Project {
    pub slug: String,
    pub title: String,
    pub blurb: String,
    pub status: String,
    pub tags: Vec<String>,
    pub url: String,
}

impl __sdk::InModule for Project {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Project`.
///
/// Provides typed access to columns for query building.
pub struct ProjectCols {
    pub slug: __sdk::__query_builder::Col<Project, String>,
    pub title: __sdk::__query_builder::Col<Project, String>,
    pub blurb: __sdk::__query_builder::Col<Project, String>,
    pub status: __sdk::__query_builder::Col<Project, String>,
    pub tags: __sdk::__query_builder::Col<Project, Vec<String>>,
    pub url: __sdk::__query_builder::Col<Project, String>,
}

impl __sdk::__query_builder::HasCols for Project {
    type Cols = ProjectCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectCols {
            slug: __sdk::__query_builder::Col::new(table_name, "slug"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            blurb: __sdk::__query_builder::Col::new(table_name, "blurb"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            tags: __sdk::__query_builder::Col::new(table_name, "tags"),
            url: __sdk::__query_builder::Col::new(table_name, "url"),
        }
    }
}

/// Indexed column accessor struct for the table `Project`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectIxCols {
    pub slug: __sdk::__query_builder::IxCol<Project, String>,
}

impl __sdk::__query_builder::HasIxCols for Project {
    type IxCols = ProjectIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectIxCols {
            slug: __sdk::__query_builder::IxCol::new(table_name, "slug"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Project {}
