// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterUserArgs {
    pub user_identity: __sdk::Identity,
    pub email: String,
    pub display_name: String,
}

impl From<RegisterUserArgs> for super::Reducer {
    fn from(args: RegisterUserArgs) -> Self {
        Self::RegisterUser {
            user_identity: args.user_identity,
            email: args.email,
            display_name: args.display_name,
        }
    }
}

impl __sdk::InModule for RegisterUserArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_user`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_user {
    /// Request that the remote module invoke the reducer `register_user` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_user:register_user_then`] to run a callback after the reducer completes.
    fn register_user(
        &self,
        user_identity: __sdk::Identity,
        email: String,
        display_name: String,
    ) -> __sdk::Result<()> {
        self.register_user_then(user_identity, email, display_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_user` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_user_then(
        &self,
        user_identity: __sdk::Identity,
        email: String,
        display_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_user for super::RemoteReducers {
    fn register_user_then(
        &self,
        user_identity: __sdk::Identity,
        email: String,
        display_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterUserArgs {
                user_identity,
                email,
                display_name,
            },
            callback,
        )
    }
}
