// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveLogInterestArgs {
    pub container: String,
}

impl From<RemoveLogInterestArgs> for super::Reducer {
    fn from(args: RemoveLogInterestArgs) -> Self {
        Self::RemoveLogInterest {
            container: args.container,
        }
    }
}

impl __sdk::InModule for RemoveLogInterestArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_log_interest`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_log_interest {
    /// Request that the remote module invoke the reducer `remove_log_interest` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`remove_log_interest:remove_log_interest_then`] to run a callback after the reducer completes.
    fn remove_log_interest(&self, container: String) -> __sdk::Result<()> {
        self.remove_log_interest_then(container, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `remove_log_interest` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn remove_log_interest_then(
        &self,
        container: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl remove_log_interest for super::RemoteReducers {
    fn remove_log_interest_then(
        &self,
        container: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RemoveLogInterestArgs { container }, callback)
    }
}
