// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestPlanArgs {
    pub description: String,
    pub count: u32,
}

impl From<RequestPlanArgs> for super::Reducer {
    fn from(args: RequestPlanArgs) -> Self {
        Self::RequestPlan {
            description: args.description,
            count: args.count,
        }
    }
}

impl __sdk::InModule for RequestPlanArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_plan`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_plan {
    /// Request that the remote module invoke the reducer `request_plan` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_plan:request_plan_then`] to run a callback after the reducer completes.
    fn request_plan(&self, description: String, count: u32) -> __sdk::Result<()> {
        self.request_plan_then(description, count, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_plan` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_plan_then(
        &self,
        description: String,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_plan for super::RemoteReducers {
    fn request_plan_then(
        &self,
        description: String,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RequestPlanArgs { description, count }, callback)
    }
}
