// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestGenerateArgs {
    pub plan_request_id: Option<u64>,
    pub tracks_json: String,
}

impl From<RequestGenerateArgs> for super::Reducer {
    fn from(args: RequestGenerateArgs) -> Self {
        Self::RequestGenerate {
            plan_request_id: args.plan_request_id,
            tracks_json: args.tracks_json,
        }
    }
}

impl __sdk::InModule for RequestGenerateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_generate`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_generate {
    /// Request that the remote module invoke the reducer `request_generate` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_generate:request_generate_then`] to run a callback after the reducer completes.
    fn request_generate(
        &self,
        plan_request_id: Option<u64>,
        tracks_json: String,
    ) -> __sdk::Result<()> {
        self.request_generate_then(plan_request_id, tracks_json, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_generate` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_generate_then(
        &self,
        plan_request_id: Option<u64>,
        tracks_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_generate for super::RemoteReducers {
    fn request_generate_then(
        &self,
        plan_request_id: Option<u64>,
        tracks_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RequestGenerateArgs {
                plan_request_id,
                tracks_json,
            },
            callback,
        )
    }
}
