// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestMagicLinkArgs {
    pub email: String,
    pub app: String,
    pub prev_identity_hex: Option<String>,
    pub callback_url: String,
}

impl From<RequestMagicLinkArgs> for super::Reducer {
    fn from(args: RequestMagicLinkArgs) -> Self {
        Self::RequestMagicLink {
            email: args.email,
            app: args.app,
            prev_identity_hex: args.prev_identity_hex,
            callback_url: args.callback_url,
        }
    }
}

impl __sdk::InModule for RequestMagicLinkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_magic_link`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_magic_link {
    /// Request that the remote module invoke the reducer `request_magic_link` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_magic_link:request_magic_link_then`] to run a callback after the reducer completes.
    fn request_magic_link(
        &self,
        email: String,
        app: String,
        prev_identity_hex: Option<String>,
        callback_url: String,
    ) -> __sdk::Result<()> {
        self.request_magic_link_then(email, app, prev_identity_hex, callback_url, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_magic_link` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_magic_link_then(
        &self,
        email: String,
        app: String,
        prev_identity_hex: Option<String>,
        callback_url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_magic_link for super::RemoteReducers {
    fn request_magic_link_then(
        &self,
        email: String,
        app: String,
        prev_identity_hex: Option<String>,
        callback_url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RequestMagicLinkArgs {
                email,
                app,
                prev_identity_hex,
                callback_url,
            },
            callback,
        )
    }
}
