// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetGenerateFailedArgs {
    pub job_id: u64,
    pub error: String,
}

impl From<SetGenerateFailedArgs> for super::Reducer {
    fn from(args: SetGenerateFailedArgs) -> Self {
        Self::SetGenerateFailed {
            job_id: args.job_id,
            error: args.error,
        }
    }
}

impl __sdk::InModule for SetGenerateFailedArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_generate_failed`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_generate_failed {
    /// Request that the remote module invoke the reducer `set_generate_failed` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_generate_failed:set_generate_failed_then`] to run a callback after the reducer completes.
    fn set_generate_failed(&self, job_id: u64, error: String) -> __sdk::Result<()> {
        self.set_generate_failed_then(job_id, error, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_generate_failed` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_generate_failed_then(
        &self,
        job_id: u64,
        error: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_generate_failed for super::RemoteReducers {
    fn set_generate_failed_then(
        &self,
        job_id: u64,
        error: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetGenerateFailedArgs { job_id, error }, callback)
    }
}
