// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetAppConfigArgs {
    pub notes_callback: String,
    pub typewars_callback: String,
    pub admin_callback: String,
    pub deck_origin: String,
}

impl From<SetAppConfigArgs> for super::Reducer {
    fn from(args: SetAppConfigArgs) -> Self {
        Self::SetAppConfig {
            notes_callback: args.notes_callback,
            typewars_callback: args.typewars_callback,
            admin_callback: args.admin_callback,
            deck_origin: args.deck_origin,
        }
    }
}

impl __sdk::InModule for SetAppConfigArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_app_config`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_app_config {
    /// Request that the remote module invoke the reducer `set_app_config` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_app_config:set_app_config_then`] to run a callback after the reducer completes.
    fn set_app_config(
        &self,
        notes_callback: String,
        typewars_callback: String,
        admin_callback: String,
        deck_origin: String,
    ) -> __sdk::Result<()> {
        self.set_app_config_then(
            notes_callback,
            typewars_callback,
            admin_callback,
            deck_origin,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_app_config` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_app_config_then(
        &self,
        notes_callback: String,
        typewars_callback: String,
        admin_callback: String,
        deck_origin: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_app_config for super::RemoteReducers {
    fn set_app_config_then(
        &self,
        notes_callback: String,
        typewars_callback: String,
        admin_callback: String,
        deck_origin: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetAppConfigArgs {
                notes_callback,
                typewars_callback,
                admin_callback,
                deck_origin,
            },
            callback,
        )
    }
}
