// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetPlanArgs {
    pub request_id: u64,
    pub tracks_json: String,
}

impl From<SetPlanArgs> for super::Reducer {
    fn from(args: SetPlanArgs) -> Self {
        Self::SetPlan {
            request_id: args.request_id,
            tracks_json: args.tracks_json,
        }
    }
}

impl __sdk::InModule for SetPlanArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_plan`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_plan {
    /// Request that the remote module invoke the reducer `set_plan` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_plan:set_plan_then`] to run a callback after the reducer completes.
    fn set_plan(&self, request_id: u64, tracks_json: String) -> __sdk::Result<()> {
        self.set_plan_then(request_id, tracks_json, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_plan` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_plan_then(
        &self,
        request_id: u64,
        tracks_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_plan for super::RemoteReducers {
    fn set_plan_then(
        &self,
        request_id: u64,
        tracks_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetPlanArgs {
                request_id,
                tracks_json,
            },
            callback,
        )
    }
}
