// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetCommentStatusArgs {
    pub id: u64,
    pub status: String,
}

impl From<SetCommentStatusArgs> for super::Reducer {
    fn from(args: SetCommentStatusArgs) -> Self {
        Self::SetCommentStatus {
            id: args.id,
            status: args.status,
        }
    }
}

impl __sdk::InModule for SetCommentStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_comment_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_comment_status {
    /// Request that the remote module invoke the reducer `set_comment_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_comment_status:set_comment_status_then`] to run a callback after the reducer completes.
    fn set_comment_status(&self, id: u64, status: String) -> __sdk::Result<()> {
        self.set_comment_status_then(id, status, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_comment_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_comment_status_then(
        &self,
        id: u64,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_comment_status for super::RemoteReducers {
    fn set_comment_status_then(
        &self,
        id: u64,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetCommentStatusArgs { id, status }, callback)
    }
}
