// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetCommentStatusWithReasonArgs {
    pub id: u64,
    pub status: String,
    pub reason: String,
}

impl From<SetCommentStatusWithReasonArgs> for super::Reducer {
    fn from(args: SetCommentStatusWithReasonArgs) -> Self {
        Self::SetCommentStatusWithReason {
            id: args.id,
            status: args.status,
            reason: args.reason,
        }
    }
}

impl __sdk::InModule for SetCommentStatusWithReasonArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_comment_status_with_reason`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_comment_status_with_reason {
    /// Request that the remote module invoke the reducer `set_comment_status_with_reason` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_comment_status_with_reason:set_comment_status_with_reason_then`] to run a callback after the reducer completes.
    fn set_comment_status_with_reason(
        &self,
        id: u64,
        status: String,
        reason: String,
    ) -> __sdk::Result<()> {
        self.set_comment_status_with_reason_then(id, status, reason, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_comment_status_with_reason` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_comment_status_with_reason_then(
        &self,
        id: u64,
        status: String,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_comment_status_with_reason for super::RemoteReducers {
    fn set_comment_status_with_reason_then(
        &self,
        id: u64,
        status: String,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetCommentStatusWithReasonArgs { id, status, reason },
            callback,
        )
    }
}
