// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetGenerateDoneArgs {
    pub job_id: u64,
    pub zip_url: String,
}

impl From<SetGenerateDoneArgs> for super::Reducer {
    fn from(args: SetGenerateDoneArgs) -> Self {
        Self::SetGenerateDone {
            job_id: args.job_id,
            zip_url: args.zip_url,
        }
    }
}

impl __sdk::InModule for SetGenerateDoneArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_generate_done`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_generate_done {
    /// Request that the remote module invoke the reducer `set_generate_done` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_generate_done:set_generate_done_then`] to run a callback after the reducer completes.
    fn set_generate_done(&self, job_id: u64, zip_url: String) -> __sdk::Result<()> {
        self.set_generate_done_then(job_id, zip_url, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_generate_done` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_generate_done_then(
        &self,
        job_id: u64,
        zip_url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_generate_done for super::RemoteReducers {
    fn set_generate_done_then(
        &self,
        job_id: u64,
        zip_url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetGenerateDoneArgs { job_id, zip_url }, callback)
    }
}
