// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitUserCommentArgs {
    pub post_slug: String,
    pub body: String,
}

impl From<SubmitUserCommentArgs> for super::Reducer {
    fn from(args: SubmitUserCommentArgs) -> Self {
        Self::SubmitUserComment {
            post_slug: args.post_slug,
            body: args.body,
        }
    }
}

impl __sdk::InModule for SubmitUserCommentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_user_comment`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_user_comment {
    /// Request that the remote module invoke the reducer `submit_user_comment` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_user_comment:submit_user_comment_then`] to run a callback after the reducer completes.
    fn submit_user_comment(&self, post_slug: String, body: String) -> __sdk::Result<()> {
        self.submit_user_comment_then(post_slug, body, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `submit_user_comment` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_user_comment_then(
        &self,
        post_slug: String,
        body: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_user_comment for super::RemoteReducers {
    fn submit_user_comment_then(
        &self,
        post_slug: String,
        body: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SubmitUserCommentArgs { post_slug, body }, callback)
    }
}
