// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::system_metrics_type::SystemMetrics;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `system_metrics`.
///
/// Obtain a handle from the [`SystemMetricsTableAccess::system_metrics`] method on [`super::RemoteTables`],
/// like `ctx.db.system_metrics()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.system_metrics().on_insert(...)`.
pub struct SystemMetricsTableHandle<'ctx> {
    imp: __sdk::TableHandle<SystemMetrics>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `system_metrics`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SystemMetricsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SystemMetricsTableHandle`], which mediates access to the table `system_metrics`.
    fn system_metrics(&self) -> SystemMetricsTableHandle<'_>;
}

impl SystemMetricsTableAccess for super::RemoteTables {
    fn system_metrics(&self) -> SystemMetricsTableHandle<'_> {
        SystemMetricsTableHandle {
            imp: self.imp.get_table::<SystemMetrics>("system_metrics"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SystemMetricsInsertCallbackId(__sdk::CallbackId);
pub struct SystemMetricsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SystemMetricsTableHandle<'ctx> {
    type Row = SystemMetrics;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SystemMetrics> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SystemMetricsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SystemMetricsInsertCallbackId {
        SystemMetricsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SystemMetricsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SystemMetricsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SystemMetricsDeleteCallbackId {
        SystemMetricsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SystemMetricsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SystemMetricsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SystemMetricsTableHandle<'ctx> {
    type UpdateCallbackId = SystemMetricsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SystemMetricsUpdateCallbackId {
        SystemMetricsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SystemMetricsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `system_metrics`,
/// which allows point queries on the field of the same name
/// via the [`SystemMetricsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.system_metrics().id().find(...)`.
pub struct SystemMetricsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SystemMetrics, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SystemMetricsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `system_metrics`.
    pub fn id(&self) -> SystemMetricsIdUnique<'ctx> {
        SystemMetricsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SystemMetricsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SystemMetrics> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SystemMetrics>("system_metrics");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SystemMetrics>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SystemMetrics>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SystemMetrics`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait system_metricsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SystemMetrics`.
    fn system_metrics(&self) -> __sdk::__query_builder::Table<SystemMetrics>;
}

impl system_metricsQueryTableAccess for __sdk::QueryTableAccessor {
    fn system_metrics(&self) -> __sdk::__query_builder::Table<SystemMetrics> {
        __sdk::__query_builder::Table::new("system_metrics")
    }
}
