// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SystemMetrics {
    pub id: u64,
    pub cpu_pct: f32,
    pub cores: u32,
    pub mem_used_gb: f32,
    pub mem_total_gb: f32,
    pub mem_pct: f32,
    pub swap_used_mb: u32,
    pub swap_total_mb: u32,
    pub disk_used_gb: u32,
    pub disk_total_gb: u32,
    pub disk_pct: f32,
    pub net_tx_bytes: u64,
    pub net_rx_bytes: u64,
    pub uptime_s: u64,
    pub gpu_pct: Option<u32>,
    pub gpu_vram_used_mb: Option<u32>,
    pub gpu_vram_total_mb: Option<u32>,
    pub gpu_temp_c: Option<u32>,
    pub gpu_model: Option<String>,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SystemMetrics {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SystemMetrics`.
///
/// Provides typed access to columns for query building.
pub struct SystemMetricsCols {
    pub id: __sdk::__query_builder::Col<SystemMetrics, u64>,
    pub cpu_pct: __sdk::__query_builder::Col<SystemMetrics, f32>,
    pub cores: __sdk::__query_builder::Col<SystemMetrics, u32>,
    pub mem_used_gb: __sdk::__query_builder::Col<SystemMetrics, f32>,
    pub mem_total_gb: __sdk::__query_builder::Col<SystemMetrics, f32>,
    pub mem_pct: __sdk::__query_builder::Col<SystemMetrics, f32>,
    pub swap_used_mb: __sdk::__query_builder::Col<SystemMetrics, u32>,
    pub swap_total_mb: __sdk::__query_builder::Col<SystemMetrics, u32>,
    pub disk_used_gb: __sdk::__query_builder::Col<SystemMetrics, u32>,
    pub disk_total_gb: __sdk::__query_builder::Col<SystemMetrics, u32>,
    pub disk_pct: __sdk::__query_builder::Col<SystemMetrics, f32>,
    pub net_tx_bytes: __sdk::__query_builder::Col<SystemMetrics, u64>,
    pub net_rx_bytes: __sdk::__query_builder::Col<SystemMetrics, u64>,
    pub uptime_s: __sdk::__query_builder::Col<SystemMetrics, u64>,
    pub gpu_pct: __sdk::__query_builder::Col<SystemMetrics, Option<u32>>,
    pub gpu_vram_used_mb: __sdk::__query_builder::Col<SystemMetrics, Option<u32>>,
    pub gpu_vram_total_mb: __sdk::__query_builder::Col<SystemMetrics, Option<u32>>,
    pub gpu_temp_c: __sdk::__query_builder::Col<SystemMetrics, Option<u32>>,
    pub gpu_model: __sdk::__query_builder::Col<SystemMetrics, Option<String>>,
    pub updated_at: __sdk::__query_builder::Col<SystemMetrics, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SystemMetrics {
    type Cols = SystemMetricsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SystemMetricsCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            cpu_pct: __sdk::__query_builder::Col::new(table_name, "cpu_pct"),
            cores: __sdk::__query_builder::Col::new(table_name, "cores"),
            mem_used_gb: __sdk::__query_builder::Col::new(table_name, "mem_used_gb"),
            mem_total_gb: __sdk::__query_builder::Col::new(table_name, "mem_total_gb"),
            mem_pct: __sdk::__query_builder::Col::new(table_name, "mem_pct"),
            swap_used_mb: __sdk::__query_builder::Col::new(table_name, "swap_used_mb"),
            swap_total_mb: __sdk::__query_builder::Col::new(table_name, "swap_total_mb"),
            disk_used_gb: __sdk::__query_builder::Col::new(table_name, "disk_used_gb"),
            disk_total_gb: __sdk::__query_builder::Col::new(table_name, "disk_total_gb"),
            disk_pct: __sdk::__query_builder::Col::new(table_name, "disk_pct"),
            net_tx_bytes: __sdk::__query_builder::Col::new(table_name, "net_tx_bytes"),
            net_rx_bytes: __sdk::__query_builder::Col::new(table_name, "net_rx_bytes"),
            uptime_s: __sdk::__query_builder::Col::new(table_name, "uptime_s"),
            gpu_pct: __sdk::__query_builder::Col::new(table_name, "gpu_pct"),
            gpu_vram_used_mb: __sdk::__query_builder::Col::new(table_name, "gpu_vram_used_mb"),
            gpu_vram_total_mb: __sdk::__query_builder::Col::new(table_name, "gpu_vram_total_mb"),
            gpu_temp_c: __sdk::__query_builder::Col::new(table_name, "gpu_temp_c"),
            gpu_model: __sdk::__query_builder::Col::new(table_name, "gpu_model"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SystemMetrics`.
///
/// Provides typed access to indexed columns for query building.
pub struct SystemMetricsIxCols {
    pub id: __sdk::__query_builder::IxCol<SystemMetrics, u64>,
}

impl __sdk::__query_builder::HasIxCols for SystemMetrics {
    type IxCols = SystemMetricsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SystemMetricsIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SystemMetrics {}
