// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertContainerStatusArgs {
    pub name: String,
    pub status: String,
    pub image: String,
    pub uptime_s: u64,
    pub mem_used_mb: u32,
    pub mem_limit_mb: u32,
    pub restart_count: u32,
}

impl From<UpsertContainerStatusArgs> for super::Reducer {
    fn from(args: UpsertContainerStatusArgs) -> Self {
        Self::UpsertContainerStatus {
            name: args.name,
            status: args.status,
            image: args.image,
            uptime_s: args.uptime_s,
            mem_used_mb: args.mem_used_mb,
            mem_limit_mb: args.mem_limit_mb,
            restart_count: args.restart_count,
        }
    }
}

impl __sdk::InModule for UpsertContainerStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_container_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_container_status {
    /// Request that the remote module invoke the reducer `upsert_container_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_container_status:upsert_container_status_then`] to run a callback after the reducer completes.
    fn upsert_container_status(
        &self,
        name: String,
        status: String,
        image: String,
        uptime_s: u64,
        mem_used_mb: u32,
        mem_limit_mb: u32,
        restart_count: u32,
    ) -> __sdk::Result<()> {
        self.upsert_container_status_then(
            name,
            status,
            image,
            uptime_s,
            mem_used_mb,
            mem_limit_mb,
            restart_count,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_container_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_container_status_then(
        &self,
        name: String,
        status: String,
        image: String,
        uptime_s: u64,
        mem_used_mb: u32,
        mem_limit_mb: u32,
        restart_count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_container_status for super::RemoteReducers {
    fn upsert_container_status_then(
        &self,
        name: String,
        status: String,
        image: String,
        uptime_s: u64,
        mem_used_mb: u32,
        mem_limit_mb: u32,
        restart_count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertContainerStatusArgs {
                name,
                status,
                image,
                uptime_s,
                mem_used_mb,
                mem_limit_mb,
                restart_count,
            },
            callback,
        )
    }
}
