// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertSystemMetricsArgs {
    pub cpu_pct: f32,
    pub cores: u32,
    pub mem_used_gb: f32,
    pub mem_total_gb: f32,
    pub mem_pct: f32,
    pub swap_used_mb: u32,
    pub swap_total_mb: u32,
    pub disk_used_gb: u32,
    pub disk_total_gb: u32,
    pub disk_pct: f32,
    pub net_tx_bytes: u64,
    pub net_rx_bytes: u64,
    pub uptime_s: u64,
    pub gpu_pct: Option<u32>,
    pub gpu_vram_used_mb: Option<u32>,
    pub gpu_vram_total_mb: Option<u32>,
    pub gpu_temp_c: Option<u32>,
    pub gpu_model: Option<String>,
}

impl From<UpsertSystemMetricsArgs> for super::Reducer {
    fn from(args: UpsertSystemMetricsArgs) -> Self {
        Self::UpsertSystemMetrics {
            cpu_pct: args.cpu_pct,
            cores: args.cores,
            mem_used_gb: args.mem_used_gb,
            mem_total_gb: args.mem_total_gb,
            mem_pct: args.mem_pct,
            swap_used_mb: args.swap_used_mb,
            swap_total_mb: args.swap_total_mb,
            disk_used_gb: args.disk_used_gb,
            disk_total_gb: args.disk_total_gb,
            disk_pct: args.disk_pct,
            net_tx_bytes: args.net_tx_bytes,
            net_rx_bytes: args.net_rx_bytes,
            uptime_s: args.uptime_s,
            gpu_pct: args.gpu_pct,
            gpu_vram_used_mb: args.gpu_vram_used_mb,
            gpu_vram_total_mb: args.gpu_vram_total_mb,
            gpu_temp_c: args.gpu_temp_c,
            gpu_model: args.gpu_model,
        }
    }
}

impl __sdk::InModule for UpsertSystemMetricsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_system_metrics`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_system_metrics {
    /// Request that the remote module invoke the reducer `upsert_system_metrics` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_system_metrics:upsert_system_metrics_then`] to run a callback after the reducer completes.
    fn upsert_system_metrics(
        &self,
        cpu_pct: f32,
        cores: u32,
        mem_used_gb: f32,
        mem_total_gb: f32,
        mem_pct: f32,
        swap_used_mb: u32,
        swap_total_mb: u32,
        disk_used_gb: u32,
        disk_total_gb: u32,
        disk_pct: f32,
        net_tx_bytes: u64,
        net_rx_bytes: u64,
        uptime_s: u64,
        gpu_pct: Option<u32>,
        gpu_vram_used_mb: Option<u32>,
        gpu_vram_total_mb: Option<u32>,
        gpu_temp_c: Option<u32>,
        gpu_model: Option<String>,
    ) -> __sdk::Result<()> {
        self.upsert_system_metrics_then(
            cpu_pct,
            cores,
            mem_used_gb,
            mem_total_gb,
            mem_pct,
            swap_used_mb,
            swap_total_mb,
            disk_used_gb,
            disk_total_gb,
            disk_pct,
            net_tx_bytes,
            net_rx_bytes,
            uptime_s,
            gpu_pct,
            gpu_vram_used_mb,
            gpu_vram_total_mb,
            gpu_temp_c,
            gpu_model,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_system_metrics` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_system_metrics_then(
        &self,
        cpu_pct: f32,
        cores: u32,
        mem_used_gb: f32,
        mem_total_gb: f32,
        mem_pct: f32,
        swap_used_mb: u32,
        swap_total_mb: u32,
        disk_used_gb: u32,
        disk_total_gb: u32,
        disk_pct: f32,
        net_tx_bytes: u64,
        net_rx_bytes: u64,
        uptime_s: u64,
        gpu_pct: Option<u32>,
        gpu_vram_used_mb: Option<u32>,
        gpu_vram_total_mb: Option<u32>,
        gpu_temp_c: Option<u32>,
        gpu_model: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_system_metrics for super::RemoteReducers {
    fn upsert_system_metrics_then(
        &self,
        cpu_pct: f32,
        cores: u32,
        mem_used_gb: f32,
        mem_total_gb: f32,
        mem_pct: f32,
        swap_used_mb: u32,
        swap_total_mb: u32,
        disk_used_gb: u32,
        disk_total_gb: u32,
        disk_pct: f32,
        net_tx_bytes: u64,
        net_rx_bytes: u64,
        uptime_s: u64,
        gpu_pct: Option<u32>,
        gpu_vram_used_mb: Option<u32>,
        gpu_vram_total_mb: Option<u32>,
        gpu_temp_c: Option<u32>,
        gpu_model: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertSystemMetricsArgs {
                cpu_pct,
                cores,
                mem_used_gb,
                mem_total_gb,
                mem_pct,
                swap_used_mb,
                swap_total_mb,
                disk_used_gb,
                disk_total_gb,
                disk_pct,
                net_tx_bytes,
                net_rx_bytes,
                uptime_s,
                gpu_pct,
                gpu_vram_used_mb,
                gpu_vram_total_mb,
                gpu_temp_c,
                gpu_model,
            },
            callback,
        )
    }
}
