// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertProjectArgs {
    pub slug: String,
    pub title: String,
    pub blurb: String,
    pub status: String,
    pub tags: Vec<String>,
    pub url: String,
}

impl From<UpsertProjectArgs> for super::Reducer {
    fn from(args: UpsertProjectArgs) -> Self {
        Self::UpsertProject {
            slug: args.slug,
            title: args.title,
            blurb: args.blurb,
            status: args.status,
            tags: args.tags,
            url: args.url,
        }
    }
}

impl __sdk::InModule for UpsertProjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_project`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_project {
    /// Request that the remote module invoke the reducer `upsert_project` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_project:upsert_project_then`] to run a callback after the reducer completes.
    fn upsert_project(
        &self,
        slug: String,
        title: String,
        blurb: String,
        status: String,
        tags: Vec<String>,
        url: String,
    ) -> __sdk::Result<()> {
        self.upsert_project_then(slug, title, blurb, status, tags, url, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_project` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_project_then(
        &self,
        slug: String,
        title: String,
        blurb: String,
        status: String,
        tags: Vec<String>,
        url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_project for super::RemoteReducers {
    fn upsert_project_then(
        &self,
        slug: String,
        title: String,
        blurb: String,
        status: String,
        tags: Vec<String>,
        url: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertProjectArgs {
                slug,
                title,
                blurb,
                status,
                tags,
                url,
            },
            callback,
        )
    }
}
