// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct User {
    pub identity: __sdk::Identity,
    pub email: String,
    pub display_name: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for User {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `User`.
///
/// Provides typed access to columns for query building.
pub struct UserCols {
    pub identity: __sdk::__query_builder::Col<User, __sdk::Identity>,
    pub email: __sdk::__query_builder::Col<User, String>,
    pub display_name: __sdk::__query_builder::Col<User, String>,
    pub created_at: __sdk::__query_builder::Col<User, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for User {
    type Cols = UserCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `User`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserIxCols {
    pub email: __sdk::__query_builder::IxCol<User, String>,
    pub identity: __sdk::__query_builder::IxCol<User, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for User {
    type IxCols = UserIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserIxCols {
            email: __sdk::__query_builder::IxCol::new(table_name, "email"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for User {}
