// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct VerifyTokenArgs {
    pub token: String,
    pub display_name: String,
}

impl From<VerifyTokenArgs> for super::Reducer {
    fn from(args: VerifyTokenArgs) -> Self {
        Self::VerifyToken {
            token: args.token,
            display_name: args.display_name,
        }
    }
}

impl __sdk::InModule for VerifyTokenArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `verify_token`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait verify_token {
    /// Request that the remote module invoke the reducer `verify_token` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`verify_token:verify_token_then`] to run a callback after the reducer completes.
    fn verify_token(&self, token: String, display_name: String) -> __sdk::Result<()> {
        self.verify_token_then(token, display_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `verify_token` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn verify_token_then(
        &self,
        token: String,
        display_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl verify_token for super::RemoteReducers {
    fn verify_token_then(
        &self,
        token: String,
        display_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            VerifyTokenArgs {
                token,
                display_name,
            },
            callback,
        )
    }
}
