// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BattleSession {
    pub id: u64,
    pub player_identity: __sdk::Identity,
    pub region_id: u32,
    pub started_at: __sdk::Timestamp,
    pub streak: u32,
    pub multiplier: f32,
    pub accuracy_hits: u32,
    pub accuracy_misses: u32,
    pub damage_dealt: u64,
    pub words_spawned: u32,
    pub active: bool,
}

impl __sdk::InModule for BattleSession {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BattleSession`.
///
/// Provides typed access to columns for query building.
pub struct BattleSessionCols {
    pub id: __sdk::__query_builder::Col<BattleSession, u64>,
    pub player_identity: __sdk::__query_builder::Col<BattleSession, __sdk::Identity>,
    pub region_id: __sdk::__query_builder::Col<BattleSession, u32>,
    pub started_at: __sdk::__query_builder::Col<BattleSession, __sdk::Timestamp>,
    pub streak: __sdk::__query_builder::Col<BattleSession, u32>,
    pub multiplier: __sdk::__query_builder::Col<BattleSession, f32>,
    pub accuracy_hits: __sdk::__query_builder::Col<BattleSession, u32>,
    pub accuracy_misses: __sdk::__query_builder::Col<BattleSession, u32>,
    pub damage_dealt: __sdk::__query_builder::Col<BattleSession, u64>,
    pub words_spawned: __sdk::__query_builder::Col<BattleSession, u32>,
    pub active: __sdk::__query_builder::Col<BattleSession, bool>,
}

impl __sdk::__query_builder::HasCols for BattleSession {
    type Cols = BattleSessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BattleSessionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            player_identity: __sdk::__query_builder::Col::new(table_name, "player_identity"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            streak: __sdk::__query_builder::Col::new(table_name, "streak"),
            multiplier: __sdk::__query_builder::Col::new(table_name, "multiplier"),
            accuracy_hits: __sdk::__query_builder::Col::new(table_name, "accuracy_hits"),
            accuracy_misses: __sdk::__query_builder::Col::new(table_name, "accuracy_misses"),
            damage_dealt: __sdk::__query_builder::Col::new(table_name, "damage_dealt"),
            words_spawned: __sdk::__query_builder::Col::new(table_name, "words_spawned"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
        }
    }
}

/// Indexed column accessor struct for the table `BattleSession`.
///
/// Provides typed access to indexed columns for query building.
pub struct BattleSessionIxCols {
    pub id: __sdk::__query_builder::IxCol<BattleSession, u64>,
    pub player_identity: __sdk::__query_builder::IxCol<BattleSession, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for BattleSession {
    type IxCols = BattleSessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BattleSessionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            player_identity: __sdk::__query_builder::IxCol::new(table_name, "player_identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BattleSession {}
