// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::battle_session_type::BattleSession;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `battle_session`.
///
/// Obtain a handle from the [`BattleSessionTableAccess::battle_session`] method on [`super::RemoteTables`],
/// like `ctx.db.battle_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.battle_session().on_insert(...)`.
pub struct BattleSessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<BattleSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `battle_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BattleSessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BattleSessionTableHandle`], which mediates access to the table `battle_session`.
    fn battle_session(&self) -> BattleSessionTableHandle<'_>;
}

impl BattleSessionTableAccess for super::RemoteTables {
    fn battle_session(&self) -> BattleSessionTableHandle<'_> {
        BattleSessionTableHandle {
            imp: self.imp.get_table::<BattleSession>("battle_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BattleSessionInsertCallbackId(__sdk::CallbackId);
pub struct BattleSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BattleSessionTableHandle<'ctx> {
    type Row = BattleSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BattleSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BattleSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BattleSessionInsertCallbackId {
        BattleSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BattleSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BattleSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BattleSessionDeleteCallbackId {
        BattleSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BattleSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BattleSessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BattleSessionTableHandle<'ctx> {
    type UpdateCallbackId = BattleSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BattleSessionUpdateCallbackId {
        BattleSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BattleSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `battle_session`,
/// which allows point queries on the field of the same name
/// via the [`BattleSessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.battle_session().id().find(...)`.
pub struct BattleSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BattleSession, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BattleSessionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `battle_session`.
    pub fn id(&self) -> BattleSessionIdUnique<'ctx> {
        BattleSessionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BattleSessionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<BattleSession> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BattleSession>("battle_session");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BattleSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BattleSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BattleSession`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait battle_sessionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BattleSession`.
    fn battle_session(&self) -> __sdk::__query_builder::Table<BattleSession>;
}

impl battle_sessionQueryTableAccess for __sdk::QueryTableAccessor {
    fn battle_session(&self) -> __sdk::__query_builder::Table<BattleSession> {
        __sdk::__query_builder::Table::new("battle_session")
    }
}
