// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimProgressArgs {
    pub prev_identity: __sdk::Identity,
    pub new_identity: __sdk::Identity,
    pub email: String,
}

impl From<ClaimProgressArgs> for super::Reducer {
    fn from(args: ClaimProgressArgs) -> Self {
        Self::ClaimProgress {
            prev_identity: args.prev_identity,
            new_identity: args.new_identity,
            email: args.email,
        }
    }
}

impl __sdk::InModule for ClaimProgressArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_progress`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_progress {
    /// Request that the remote module invoke the reducer `claim_progress` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_progress:claim_progress_then`] to run a callback after the reducer completes.
    fn claim_progress(
        &self,
        prev_identity: __sdk::Identity,
        new_identity: __sdk::Identity,
        email: String,
    ) -> __sdk::Result<()> {
        self.claim_progress_then(prev_identity, new_identity, email, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_progress` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_progress_then(
        &self,
        prev_identity: __sdk::Identity,
        new_identity: __sdk::Identity,
        email: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_progress for super::RemoteReducers {
    fn claim_progress_then(
        &self,
        prev_identity: __sdk::Identity,
        new_identity: __sdk::Identity,
        email: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ClaimProgressArgs {
                prev_identity,
                new_identity,
                email,
            },
            callback,
        )
    }
}
