// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimProgressSelfArgs {
    pub prev_identity: __sdk::Identity,
    pub email: String,
}

impl From<ClaimProgressSelfArgs> for super::Reducer {
    fn from(args: ClaimProgressSelfArgs) -> Self {
        Self::ClaimProgressSelf {
            prev_identity: args.prev_identity,
            email: args.email,
        }
    }
}

impl __sdk::InModule for ClaimProgressSelfArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_progress_self`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_progress_self {
    /// Request that the remote module invoke the reducer `claim_progress_self` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_progress_self:claim_progress_self_then`] to run a callback after the reducer completes.
    fn claim_progress_self(
        &self,
        prev_identity: __sdk::Identity,
        email: String,
    ) -> __sdk::Result<()> {
        self.claim_progress_self_then(prev_identity, email, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_progress_self` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_progress_self_then(
        &self,
        prev_identity: __sdk::Identity,
        email: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_progress_self for super::RemoteReducers {
    fn claim_progress_self_then(
        &self,
        prev_identity: __sdk::Identity,
        email: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ClaimProgressSelfArgs {
                prev_identity,
                email,
            },
            callback,
        )
    }
}
