// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GlobalWar {
    pub id: u32,
    pub season: u32,
    pub enemy_territories: u32,
    pub liberated_territories: u32,
    pub season_start: __sdk::Timestamp,
}

impl __sdk::InModule for GlobalWar {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GlobalWar`.
///
/// Provides typed access to columns for query building.
pub struct GlobalWarCols {
    pub id: __sdk::__query_builder::Col<GlobalWar, u32>,
    pub season: __sdk::__query_builder::Col<GlobalWar, u32>,
    pub enemy_territories: __sdk::__query_builder::Col<GlobalWar, u32>,
    pub liberated_territories: __sdk::__query_builder::Col<GlobalWar, u32>,
    pub season_start: __sdk::__query_builder::Col<GlobalWar, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for GlobalWar {
    type Cols = GlobalWarCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GlobalWarCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            season: __sdk::__query_builder::Col::new(table_name, "season"),
            enemy_territories: __sdk::__query_builder::Col::new(table_name, "enemy_territories"),
            liberated_territories: __sdk::__query_builder::Col::new(
                table_name,
                "liberated_territories",
            ),
            season_start: __sdk::__query_builder::Col::new(table_name, "season_start"),
        }
    }
}

/// Indexed column accessor struct for the table `GlobalWar`.
///
/// Provides typed access to indexed columns for query building.
pub struct GlobalWarIxCols {
    pub id: __sdk::__query_builder::IxCol<GlobalWar, u32>,
}

impl __sdk::__query_builder::HasIxCols for GlobalWar {
    type IxCols = GlobalWarIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GlobalWarIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GlobalWar {}
