// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::global_war_type::GlobalWar;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `global_war`.
///
/// Obtain a handle from the [`GlobalWarTableAccess::global_war`] method on [`super::RemoteTables`],
/// like `ctx.db.global_war()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.global_war().on_insert(...)`.
pub struct GlobalWarTableHandle<'ctx> {
    imp: __sdk::TableHandle<GlobalWar>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `global_war`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GlobalWarTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GlobalWarTableHandle`], which mediates access to the table `global_war`.
    fn global_war(&self) -> GlobalWarTableHandle<'_>;
}

impl GlobalWarTableAccess for super::RemoteTables {
    fn global_war(&self) -> GlobalWarTableHandle<'_> {
        GlobalWarTableHandle {
            imp: self.imp.get_table::<GlobalWar>("global_war"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GlobalWarInsertCallbackId(__sdk::CallbackId);
pub struct GlobalWarDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GlobalWarTableHandle<'ctx> {
    type Row = GlobalWar;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GlobalWar> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GlobalWarInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalWarInsertCallbackId {
        GlobalWarInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GlobalWarInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GlobalWarDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalWarDeleteCallbackId {
        GlobalWarDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GlobalWarDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GlobalWarUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GlobalWarTableHandle<'ctx> {
    type UpdateCallbackId = GlobalWarUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GlobalWarUpdateCallbackId {
        GlobalWarUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GlobalWarUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `global_war`,
/// which allows point queries on the field of the same name
/// via the [`GlobalWarIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.global_war().id().find(...)`.
pub struct GlobalWarIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GlobalWar, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GlobalWarTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `global_war`.
    pub fn id(&self) -> GlobalWarIdUnique<'ctx> {
        GlobalWarIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GlobalWarIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<GlobalWar> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GlobalWar>("global_war");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GlobalWar>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GlobalWar>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GlobalWar`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait global_warQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GlobalWar`.
    fn global_war(&self) -> __sdk::__query_builder::Table<GlobalWar>;
}

impl global_warQueryTableAccess for __sdk::QueryTableAccessor {
    fn global_war(&self) -> __sdk::__query_builder::Table<GlobalWar> {
        __sdk::__query_builder::Table::new("global_war")
    }
}
