// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub identity: __sdk::Identity,
    pub username: String,
    pub legion: u8,
    pub total_damage: u64,
    pub season_damage: u64,
    pub best_wpm: u32,
    pub joined_at: __sdk::Timestamp,
    pub email: Option<String>,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub identity: __sdk::__query_builder::Col<Player, __sdk::Identity>,
    pub username: __sdk::__query_builder::Col<Player, String>,
    pub legion: __sdk::__query_builder::Col<Player, u8>,
    pub total_damage: __sdk::__query_builder::Col<Player, u64>,
    pub season_damage: __sdk::__query_builder::Col<Player, u64>,
    pub best_wpm: __sdk::__query_builder::Col<Player, u32>,
    pub joined_at: __sdk::__query_builder::Col<Player, __sdk::Timestamp>,
    pub email: __sdk::__query_builder::Col<Player, Option<String>>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            legion: __sdk::__query_builder::Col::new(table_name, "legion"),
            total_damage: __sdk::__query_builder::Col::new(table_name, "total_damage"),
            season_damage: __sdk::__query_builder::Col::new(table_name, "season_damage"),
            best_wpm: __sdk::__query_builder::Col::new(table_name, "best_wpm"),
            joined_at: __sdk::__query_builder::Col::new(table_name, "joined_at"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub identity: __sdk::__query_builder::IxCol<Player, __sdk::Identity>,
    pub username: __sdk::__query_builder::IxCol<Player, String>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
            username: __sdk::__query_builder::IxCol::new(table_name, "username"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}
