// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Region {
    pub id: u32,
    pub name: String,
    pub tier: u8,
    pub controlling_legion: i8,
    pub enemy_hp: u64,
    pub enemy_max_hp: u64,
    pub regen_rate: u64,
    pub damage_0: u64,
    pub damage_1: u64,
    pub damage_2: u64,
    pub damage_3: u64,
    pub damage_4: u64,
    pub active_wardens: u32,
}

impl __sdk::InModule for Region {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Region`.
///
/// Provides typed access to columns for query building.
pub struct RegionCols {
    pub id: __sdk::__query_builder::Col<Region, u32>,
    pub name: __sdk::__query_builder::Col<Region, String>,
    pub tier: __sdk::__query_builder::Col<Region, u8>,
    pub controlling_legion: __sdk::__query_builder::Col<Region, i8>,
    pub enemy_hp: __sdk::__query_builder::Col<Region, u64>,
    pub enemy_max_hp: __sdk::__query_builder::Col<Region, u64>,
    pub regen_rate: __sdk::__query_builder::Col<Region, u64>,
    pub damage_0: __sdk::__query_builder::Col<Region, u64>,
    pub damage_1: __sdk::__query_builder::Col<Region, u64>,
    pub damage_2: __sdk::__query_builder::Col<Region, u64>,
    pub damage_3: __sdk::__query_builder::Col<Region, u64>,
    pub damage_4: __sdk::__query_builder::Col<Region, u64>,
    pub active_wardens: __sdk::__query_builder::Col<Region, u32>,
}

impl __sdk::__query_builder::HasCols for Region {
    type Cols = RegionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RegionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            tier: __sdk::__query_builder::Col::new(table_name, "tier"),
            controlling_legion: __sdk::__query_builder::Col::new(table_name, "controlling_legion"),
            enemy_hp: __sdk::__query_builder::Col::new(table_name, "enemy_hp"),
            enemy_max_hp: __sdk::__query_builder::Col::new(table_name, "enemy_max_hp"),
            regen_rate: __sdk::__query_builder::Col::new(table_name, "regen_rate"),
            damage_0: __sdk::__query_builder::Col::new(table_name, "damage_0"),
            damage_1: __sdk::__query_builder::Col::new(table_name, "damage_1"),
            damage_2: __sdk::__query_builder::Col::new(table_name, "damage_2"),
            damage_3: __sdk::__query_builder::Col::new(table_name, "damage_3"),
            damage_4: __sdk::__query_builder::Col::new(table_name, "damage_4"),
            active_wardens: __sdk::__query_builder::Col::new(table_name, "active_wardens"),
        }
    }
}

/// Indexed column accessor struct for the table `Region`.
///
/// Provides typed access to indexed columns for query building.
pub struct RegionIxCols {
    pub id: __sdk::__query_builder::IxCol<Region, u32>,
}

impl __sdk::__query_builder::HasIxCols for Region {
    type IxCols = RegionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RegionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Region {}
