// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::region_type::Region;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `region`.
///
/// Obtain a handle from the [`RegionTableAccess::region`] method on [`super::RemoteTables`],
/// like `ctx.db.region()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.region().on_insert(...)`.
pub struct RegionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Region>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `region`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RegionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RegionTableHandle`], which mediates access to the table `region`.
    fn region(&self) -> RegionTableHandle<'_>;
}

impl RegionTableAccess for super::RemoteTables {
    fn region(&self) -> RegionTableHandle<'_> {
        RegionTableHandle {
            imp: self.imp.get_table::<Region>("region"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RegionInsertCallbackId(__sdk::CallbackId);
pub struct RegionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RegionTableHandle<'ctx> {
    type Row = Region;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Region> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RegionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegionInsertCallbackId {
        RegionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RegionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RegionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegionDeleteCallbackId {
        RegionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RegionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RegionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RegionTableHandle<'ctx> {
    type UpdateCallbackId = RegionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RegionUpdateCallbackId {
        RegionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RegionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `region`,
/// which allows point queries on the field of the same name
/// via the [`RegionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.region().id().find(...)`.
pub struct RegionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Region, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RegionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `region`.
    pub fn id(&self) -> RegionIdUnique<'ctx> {
        RegionIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RegionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Region> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Region>("region");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Region>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Region>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Region`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait regionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Region`.
    fn region(&self) -> __sdk::__query_builder::Table<Region>;
}

impl regionQueryTableAccess for __sdk::QueryTableAccessor {
    fn region(&self) -> __sdk::__query_builder::Table<Region> {
        __sdk::__query_builder::Table::new("region")
    }
}
