// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartBattleArgs {
    pub region_id: u32,
}

impl From<StartBattleArgs> for super::Reducer {
    fn from(args: StartBattleArgs) -> Self {
        Self::StartBattle {
            region_id: args.region_id,
        }
    }
}

impl __sdk::InModule for StartBattleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_battle`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_battle {
    /// Request that the remote module invoke the reducer `start_battle` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`start_battle:start_battle_then`] to run a callback after the reducer completes.
    fn start_battle(&self, region_id: u32) -> __sdk::Result<()> {
        self.start_battle_then(region_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `start_battle` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn start_battle_then(
        &self,
        region_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl start_battle for super::RemoteReducers {
    fn start_battle_then(
        &self,
        region_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(StartBattleArgs { region_id }, callback)
    }
}
