// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitWordArgs {
    pub session_id: u64,
    pub word: String,
}

impl From<SubmitWordArgs> for super::Reducer {
    fn from(args: SubmitWordArgs) -> Self {
        Self::SubmitWord {
            session_id: args.session_id,
            word: args.word,
        }
    }
}

impl __sdk::InModule for SubmitWordArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_word`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_word {
    /// Request that the remote module invoke the reducer `submit_word` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_word:submit_word_then`] to run a callback after the reducer completes.
    fn submit_word(&self, session_id: u64, word: String) -> __sdk::Result<()> {
        self.submit_word_then(session_id, word, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `submit_word` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_word_then(
        &self,
        session_id: u64,
        word: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_word for super::RemoteReducers {
    fn submit_word_then(
        &self,
        session_id: u64,
        word: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SubmitWordArgs { session_id, word }, callback)
    }
}
