// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SwapLegionArgs {
    pub new_legion: u8,
}

impl From<SwapLegionArgs> for super::Reducer {
    fn from(args: SwapLegionArgs) -> Self {
        Self::SwapLegion {
            new_legion: args.new_legion,
        }
    }
}

impl __sdk::InModule for SwapLegionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `swap_legion`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait swap_legion {
    /// Request that the remote module invoke the reducer `swap_legion` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`swap_legion:swap_legion_then`] to run a callback after the reducer completes.
    fn swap_legion(&self, new_legion: u8) -> __sdk::Result<()> {
        self.swap_legion_then(new_legion, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `swap_legion` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn swap_legion_then(
        &self,
        new_legion: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl swap_legion for super::RemoteReducers {
    fn swap_legion_then(
        &self,
        new_legion: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SwapLegionArgs { new_legion }, callback)
    }
}
