// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Word {
    pub id: u64,
    pub session_id: u64,
    pub text: String,
    pub difficulty: u8,
    pub base_damage: u64,
    pub spawned_at: __sdk::Timestamp,
    pub expires_at: __sdk::Timestamp,
}

impl __sdk::InModule for Word {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Word`.
///
/// Provides typed access to columns for query building.
pub struct WordCols {
    pub id: __sdk::__query_builder::Col<Word, u64>,
    pub session_id: __sdk::__query_builder::Col<Word, u64>,
    pub text: __sdk::__query_builder::Col<Word, String>,
    pub difficulty: __sdk::__query_builder::Col<Word, u8>,
    pub base_damage: __sdk::__query_builder::Col<Word, u64>,
    pub spawned_at: __sdk::__query_builder::Col<Word, __sdk::Timestamp>,
    pub expires_at: __sdk::__query_builder::Col<Word, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Word {
    type Cols = WordCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WordCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            difficulty: __sdk::__query_builder::Col::new(table_name, "difficulty"),
            base_damage: __sdk::__query_builder::Col::new(table_name, "base_damage"),
            spawned_at: __sdk::__query_builder::Col::new(table_name, "spawned_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Word`.
///
/// Provides typed access to indexed columns for query building.
pub struct WordIxCols {
    pub id: __sdk::__query_builder::IxCol<Word, u64>,
    pub session_id: __sdk::__query_builder::IxCol<Word, u64>,
}

impl __sdk::__query_builder::HasIxCols for Word {
    type IxCols = WordIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WordIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Word {}
