// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::word_type::Word;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `word`.
///
/// Obtain a handle from the [`WordTableAccess::word`] method on [`super::RemoteTables`],
/// like `ctx.db.word()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.word().on_insert(...)`.
pub struct WordTableHandle<'ctx> {
    imp: __sdk::TableHandle<Word>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `word`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WordTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WordTableHandle`], which mediates access to the table `word`.
    fn word(&self) -> WordTableHandle<'_>;
}

impl WordTableAccess for super::RemoteTables {
    fn word(&self) -> WordTableHandle<'_> {
        WordTableHandle {
            imp: self.imp.get_table::<Word>("word"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WordInsertCallbackId(__sdk::CallbackId);
pub struct WordDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WordTableHandle<'ctx> {
    type Row = Word;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Word> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WordInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WordInsertCallbackId {
        WordInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WordInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WordDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WordDeleteCallbackId {
        WordDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WordDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WordUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WordTableHandle<'ctx> {
    type UpdateCallbackId = WordUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WordUpdateCallbackId {
        WordUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WordUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `word`,
/// which allows point queries on the field of the same name
/// via the [`WordIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.word().id().find(...)`.
pub struct WordIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Word, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WordTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `word`.
    pub fn id(&self) -> WordIdUnique<'ctx> {
        WordIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WordIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Word> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Word>("word");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Word>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Word>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Word`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait wordQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Word`.
    fn word(&self) -> __sdk::__query_builder::Table<Word>;
}

impl wordQueryTableAccess for __sdk::QueryTableAccessor {
    fn word(&self) -> __sdk::__query_builder::Table<Word> {
        __sdk::__query_builder::Table::new("word")
    }
}
