// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WordExpireSchedule {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for WordExpireSchedule {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WordExpireSchedule`.
///
/// Provides typed access to columns for query building.
pub struct WordExpireScheduleCols {
    pub scheduled_id: __sdk::__query_builder::Col<WordExpireSchedule, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<WordExpireSchedule, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for WordExpireSchedule {
    type Cols = WordExpireScheduleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WordExpireScheduleCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `WordExpireSchedule`.
///
/// Provides typed access to indexed columns for query building.
pub struct WordExpireScheduleIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<WordExpireSchedule, u64>,
}

impl __sdk::__query_builder::HasIxCols for WordExpireSchedule {
    type IxCols = WordExpireScheduleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WordExpireScheduleIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WordExpireSchedule {}
