"""Event data - 35 globalized tech-themed events."""

SASTA_EVENTS = [
    # === CASH GAIN (8 events) ===
    {
        "name": "Gateway Timeout",
        "desc": "Cannot buy property this turn",
        "type": "SKIP_BUY",
        "category": "CASH_GAIN",
        "value": 0,
    },
    {
        "name": "Tax Rebate",
        "desc": "Receive bonus cash",
        "type": "CASH_GAIN",
        "category": "CASH_GAIN",
        "value": 100,
    },
    {
        "name": "Startup Funding",
        "desc": "Receive investment",
        "type": "CASH_GAIN",
        "category": "CASH_GAIN",
        "value": 200,
    },
    {
        "name": "Crypto Moon",
        "desc": "Your crypto investment paid off",
        "type": "CASH_GAIN",
        "category": "CASH_GAIN",
        "value": 300,
    },
    {
        "name": "Viral Post",
        "desc": "Your content went viral",
        "type": "CASH_GAIN",
        "category": "CASH_GAIN",
        "value": 150,
    },
    {
        "name": "Bug Bounty",
        "desc": "Found a security vulnerability",
        "type": "CASH_GAIN",
        "category": "CASH_GAIN",
        "value": 250,
    },
    {
        "name": "Passive Income",
        "desc": "Your side project generated revenue",
        "type": "CASH_GAIN",
        "category": "CASH_GAIN",
        "value": 100,
    },
    {
        "name": "Holiday Bonus",
        "desc": "Double rent collection next turn",
        "type": "DOUBLE_RENT",
        "category": "CASH_GAIN",
        "value": 0,
    },
    # === CASH LOSS (7 events) ===
    {
        "name": "Wedding Season",
        "desc": "Pay for gifts",
        "type": "CASH_LOSS",
        "category": "CASH_LOSS",
        "value": 150,
    },
    {
        "name": "Subscription Trap",
        "desc": "Forgot to cancel that subscription",
        "type": "CASH_LOSS",
        "category": "CASH_LOSS",
        "value": 100,
    },
    {
        "name": "Phishing Attack",
        "desc": "Fell for a phishing scam",
        "type": "CASH_LOSS",
        "category": "CASH_LOSS",
        "value": 150,
    },
    {
        "name": "Data Breach Fine",
        "desc": "GDPR violation penalty",
        "type": "CASH_LOSS",
        "category": "CASH_LOSS",
        "value": 200,
    },
    {
        "name": "Crypto Crash",
        "desc": "Your crypto portfolio crashed",
        "type": "CASH_LOSS",
        "category": "CASH_LOSS",
        "value": 250,
    },
    {
        "name": "Coffee Break",
        "desc": "Skip next turn (relax!)",
        "type": "SKIP_TURN",
        "category": "CASH_LOSS",
        "value": 0,
    },
    {
        "name": "Transit Strike",
        "desc": "Move back 3 spaces",
        "type": "MOVE_BACK",
        "category": "CASH_LOSS",
        "value": 3,
    },
    # === TAKE-THAT (5 events) ===
    {
        "name": "Influencer Collab",
        "desc": "Collect from everyone",
        "type": "COLLECT_FROM_ALL",
        "category": "TARGETING",
        "value": 50,
    },
    {
        "name": "Championship Game",
        "desc": "Everyone pays you",
        "type": "COLLECT_FROM_ALL",
        "category": "TARGETING",
        "value": 25,
    },
    {
        "name": "Ransomware",
        "desc": "Steal $100 from richest player",
        "type": "STEAL_FROM_RICHEST",
        "category": "TARGETING",
        "value": 100,
    },
    {
        "name": "Identity Theft",
        "desc": "Swap cash with random player",
        "type": "SWAP_CASH",
        "category": "TARGETING",
        "value": 0,
    },
    {
        "name": "Whistleblower",
        "desc": "Reveal another player's cash",
        "type": "REVEAL_CASH",
        "category": "TARGETING",
        "value": 0,
    },
    # === SABOTAGE (6 events) ===
    {
        "name": "Lucky Hack",
        "desc": "Free property upgrade",
        "type": "FREE_UPGRADE",
        "category": "TARGETING",
        "value": 0,
    },
    {
        "name": "Deprecated",
        "desc": "Remove 1 upgrade level from any property",
        "type": "REMOVE_UPGRADE",
        "category": "TARGETING",
        "value": 0,
    },
    {
        "name": "DDoS Attack",
        "desc": "Block a tile for 2 rounds",
        "type": "BLOCK_TILE",
        "category": "TARGETING",
        "value": 2,
    },
    {
        "name": "Fork Repo",
        "desc": "Clone another player's upgrade to your property",
        "type": "CLONE_UPGRADE",
        "category": "TARGETING",
        "value": 0,
    },
    {
        "name": "Hostile Takeover",
        "desc": "Buy any property at 150% price (forced)",
        "type": "FORCE_BUY",
        "category": "TARGETING",
        "value": 150,
    },
    {
        "name": "Open Source",
        "desc": "One property becomes free to land on for 1 round",
        "type": "FREE_LANDING",
        "category": "TARGETING",
        "value": 1,
    },
    # === MOVEMENT (5 events) ===
    {
        "name": "System Restore",
        "desc": "Return to previous position",
        "type": "MOVE_TO_PREVIOUS",
        "category": "MOVEMENT",
        "value": 0,
    },
    {
        "name": "Reboot",
        "desc": "Go to GO (don't collect)",
        "type": "GO_TO_GO",
        "category": "MOVEMENT",
        "value": 0,
    },
    {
        "name": "Fast Forward",
        "desc": "Move ahead 5 spaces",
        "type": "MOVE_FORWARD",
        "category": "MOVEMENT",
        "value": 5,
    },
    {
        "name": "Backdoor Access",
        "desc": "Teleport to any unowned property",
        "type": "TELEPORT_UNOWNED",
        "category": "MOVEMENT",
        "value": 0,
    },
    {
        "name": "Traffic Jam",
        "desc": "Stay where you are next turn",
        "type": "SKIP_MOVE",
        "category": "MOVEMENT",
        "value": 0,
    },
    # === GLOBAL EFFECTS (4 events) ===
    {
        "name": "Market Crash",
        "desc": "All rent halved for 1 round",
        "type": "MARKET_CRASH",
        "category": "GLOBAL_CHAOS",
        "value": 0,
    },
    {
        "name": "Bull Market",
        "desc": "All rent +50% for 1 round",
        "type": "BULL_MARKET",
        "category": "GLOBAL_CHAOS",
        "value": 0,
    },
    {
        "name": "System Update",
        "desc": "All players skip next turn",
        "type": "ALL_SKIP_TURN",
        "category": "GLOBAL_CHAOS",
        "value": 0,
    },
    {
        "name": "Hyperinflation",
        "desc": "GO bonus triples this round",
        "type": "HYPERINFLATION",
        "category": "GLOBAL_CHAOS",
        "value": 0,
    },
]
