apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: sastaspace
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: worker
        image: localhost:32000/sastaspace-backend:latest
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: MODE
          value: "worker"
        envFrom:
        - configMapRef:
            name: sastaspace-config
        - secretRef:
            name: sastaspace-env
            optional: true
        - secretRef:
            name: sastaspace-db-auth
        volumeMounts:
        - name: sites-data
          mountPath: /data/sites
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: sites-data
        persistentVolumeClaim:
          claimName: sites-pvc
