"""Seed quiz questions and facts."""

# (question, [option1, option2, option3, option4], correct_index, category, difficulty)
QUIZ_QUESTIONS: list[tuple[str, list[str], int, str, int]] = [
    (
        "What is the second law of thermodynamics about?",
        [
            "Conservation of energy",
            "Entropy always increases",
            "Force equals mass times acceleration",
            "Every action has an equal reaction",
        ],
        1,
        "science",
        1,
    ),
    (
        "Which ancient wonder was a lighthouse?",
        ["Colossus of Rhodes", "Hanging Gardens", "Lighthouse of Alexandria", "Great Pyramid"],
        2,
        "history",
        1,
    ),
    (
        "What causes the Northern Lights?",
        ["Moonlight reflection", "Volcanic gases", "Charged solar particles", "Light pollution"],
        2,
        "science",
        1,
    ),
    (
        "How old is the oldest known living tree?",
        ["About 1,000 years", "About 3,000 years", "About 5,000 years", "About 10,000 years"],
        2,
        "science",
        2,
    ),
    (
        "What percentage of deep-sea creatures use bioluminescence?",
        ["About 25%", "About 50%", "About 76%", "About 95%"],
        2,
        "science",
        2,
    ),
    (
        "What is the Great Red Spot on Jupiter?",
        ["A volcano", "A giant storm", "An impact crater", "A magnetic anomaly"],
        1,
        "science",
        1,
    ),
    (
        "Which word comes from the Latin 'potere'?",
        ["Potential", "Power", "Position", "All of the above"],
        1,
        "language",
        2,
    ),
    (
        "How fast can a wildfire move in grasslands?",
        ["5 mph", "14 mph", "40 mph", "60 mph"],
        2,
        "science",
        2,
    ),
    (
        "What was the Tsar Bomba?",
        [
            "A Russian satellite",
            "The most powerful nuclear weapon ever detonated",
            "A volcanic eruption",
            "A type of rocket engine",
        ],
        1,
        "history",
        1,
    ),
    (
        "How much power does the human brain generate?",
        ["About 2 watts", "About 20 watts", "About 200 watts", "About 2000 watts"],
        1,
        "science",
        2,
    ),
    (
        "What can tardigrades survive?",
        ["Only extreme cold", "Only extreme heat", "The vacuum of space", "Only high pressure"],
        2,
        "science",
        1,
    ),
    (
        "How tall does Mount Everest grow each year?",
        ["About 4mm", "About 4cm", "About 4m", "It doesn't grow"],
        0,
        "geography",
        2,
    ),
    (
        "How many galaxies are in the observable universe?",
        ["About 2 million", "About 2 billion", "About 2 trillion", "About 2 quadrillion"],
        2,
        "science",
        2,
    ),
    (
        "How long did the Great Pyramid hold the record as tallest structure?",
        ["800 years", "1,800 years", "2,800 years", "3,800 years"],
        3,
        "history",
        2,
    ),
    (
        "What killed the dinosaurs?",
        ["A supervolcano", "An ice age", "An asteroid impact", "A gamma-ray burst"],
        2,
        "science",
        1,
    ),
    (
        "Is the Great Wall of China visible from space?",
        ["Yes, easily", "Yes, but barely", "No, it's a myth", "Only from the Moon"],
        2,
        "history",
        1,
    ),
    (
        "What does a supernova briefly outshine?",
        ["The Sun", "A solar system", "An entire galaxy", "The entire universe"],
        2,
        "science",
        2,
    ),
    (
        "How many neurons does the human brain have?",
        ["About 8.6 million", "About 860 million", "About 86 billion", "About 860 billion"],
        2,
        "science",
        2,
    ),
    (
        "What code did the Samurai follow?",
        ["Chivalry", "Bushido", "Dharma", "Stoicism"],
        1,
        "history",
        1,
    ),
    (
        "How long did Masada withstand Roman siege?",
        ["3 months", "3 years", "30 years", "300 years"],
        1,
        "history",
        2,
    ),
    (
        "What was more expensive than the Taj Mahal?",
        ["The Amber Room", "The Peacock Throne", "Versailles", "The Forbidden City"],
        1,
        "history",
        3,
    ),
    (
        "Forest fires help some seeds by providing what?",
        ["Nutrients", "Water", "Extreme heat to crack open", "Carbon dioxide"],
        2,
        "science",
        1,
    ),
    (
        "How much energy does the Sun produce per second compared to Earth's needs?",
        [
            "Enough for 1,000 years",
            "Enough for 50,000 years",
            "Enough for 500,000 years",
            "Enough for 5 million years",
        ],
        2,
        "science",
        3,
    ),
    (
        "Coral reefs build structures from what material?",
        ["Silicon dioxide", "Calcium carbonate", "Iron oxide", "Magnesium sulfate"],
        1,
        "science",
        2,
    ),
    (
        "How much can temperature drop during a total solar eclipse?",
        ["About 1°F", "About 5°F", "About 10°F", "About 20°F"],
        2,
        "science",
        2,
    ),
    (
        "How many scrolls were estimated lost in the Library of Alexandria?",
        ["40,000", "100,000", "400,000", "1,000,000"],
        2,
        "history",
        2,
    ),
    (
        "What do black holes spin at?",
        [
            "The speed of sound",
            "Half the speed of light",
            "Nearly the speed of light",
            "Faster than light",
        ],
        2,
        "science",
        2,
    ),
    (
        "How many connections can each neuron form?",
        ["Up to 100", "Up to 1,000", "Up to 10,000", "Up to 100,000"],
        2,
        "science",
        2,
    ),
    (
        "How long did the Lighthouse of Alexandria stand?",
        ["500 years", "1,000 years", "1,500 years", "2,000 years"],
        2,
        "history",
        2,
    ),
    (
        "What organism can repair its own DNA after radiation damage?",
        ["Humans", "Some bacteria", "Trees", "Fungi"],
        1,
        "science",
        2,
    ),
]
