require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Allow requests from development hostname
  config.hosts << "dev.sastaspace.com"

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Use Redis for caching
  config.cache_store = :redis_cache_store, { url: ENV.fetch("REDIS_URL", "redis://127.0.0.1:6379/1"), namespace: "sastaspace:cache:#{Rails.env}" }

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Use dev.sastaspace.com for all URLs in development
  # All URLs will use HTTPS protocol to match the Cloudflare proxy
  config.action_controller.default_url_options = { host: "dev.sastaspace.com", protocol: "https" }
  config.action_mailer.default_url_options = { host: "dev.sastaspace.com", protocol: "https" }

  # Configure routes to use dev.sastaspace.com
  config.after_initialize do
    Rails.application.routes.default_url_options[:host] = "dev.sastaspace.com"
    Rails.application.routes.default_url_options[:protocol] = "https"
  end

  # Configure Active Storage to use dev.sastaspace.com with HTTPS
  # This ensures all image URLs use HTTPS and match the page protocol
  config.active_storage.resolve_model_to_route = :rails_storage_proxy

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Disable verbose logging to reduce noise (only show WARN and ERROR)
  # config.active_record.verbose_query_logs = false
  # config.active_record.query_log_tags_enabled = false
  # config.active_job.verbose_enqueue_logs = false
  # config.action_dispatch.verbose_redirect_logs = false

  # Use Sidekiq for background jobs in development
  config.active_job.queue_adapter = :sidekiq

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Set log level to WARN to reduce noise (only show WARN and ERROR)
  # Override with RAILS_LOG_LEVEL environment variable if needed (e.g., RAILS_LOG_LEVEL=debug)
  config.log_level = ENV.fetch("RAILS_LOG_LEVEL", "warn").to_sym

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Configure Bullet for N+1 query detection
  # Only show warnings/errors to reduce log noise
  config.after_initialize do
    Bullet.enable = true
    Bullet.bullet_logger = false # Disable file logging to reduce noise
    Bullet.console = false # Disable console output to reduce noise
    Bullet.rails_logger = true # Keep Rails logger (respects log_level)
    Bullet.add_footer = true
    Bullet.skip_html_injection = false
  end
end
