apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: sastaspace
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-enable: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://sastaspace.com,https://*.sastaspace.com"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: public
  rules:
    - host: auth.sastaspace.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gotrue
                port:
                  number: 9999
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studio-ingress
  namespace: sastaspace
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: public
  rules:
    - host: studio.sastaspace.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: studio
                port:
                  number: 3000
