apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-fallback
  namespace: projects
  annotations:
    nginx.ingress.kubernetes.io/default-backend: landing-web
spec:
  ingressClassName: nginx
  rules:
    - host: "*.sastaspace.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-web
                port:
                  number: 80
