//! Thin wrapper over `spacetimedb-sdk` for the sastaspace TUI.
//!
//! Re-exports the auto-generated module bindings under `bindings::*` and
//! provides a `StdbHandle` that owns the connection and exposes typed
//! access to tables and reducers.
//!
//! Bindings live in `src/bindings/` (generated by `build_bindings.sh`
//! using `spacetime generate --lang rust --bin-path <wasm>`; checked in
//! per repo convention).

#![allow(clippy::all, dead_code)] // generated bindings are noisy

pub mod bindings;
pub mod connection;

pub use connection::{StdbConfig, StdbError, StdbHandle, StdbStatus};

/// Helpers that read STDB tables and convert rows into shapes app crates use.
/// Kept as a thin module here so app crates don't need to know about
/// `spacetimedb-sdk` directly.
pub mod sub_helpers {
    use crate::bindings::{
        self, comment_table::CommentTableAccess, project_table::ProjectTableAccess,
    };
    use spacetimedb_sdk::Table;

    /// Snapshot the `project` table into `app_portfolio::ProjectRow`s.
    /// Called from the shell whenever an `Updated("project")` event arrives.
    pub fn read_projects(conn: &bindings::DbConnection) -> Vec<app_portfolio::ProjectRow> {
        conn.db
            .project()
            .iter()
            .map(|p| app_portfolio::ProjectRow {
                slug: p.slug.clone(),
                title: p.title.clone(),
                blurb: p.blurb.clone(),
                status: p.status.clone(),
            })
            .collect()
    }

    /// Snapshot the `project` table into `app_notes::NoteRow`s.
    /// All projects are treated as notes for v1 (no `kind` field in schema).
    pub fn read_notes(conn: &bindings::DbConnection) -> Vec<app_notes::NoteRow> {
        conn.db
            .project()
            .iter()
            .map(|p| app_notes::NoteRow {
                slug: p.slug.clone(),
                title: p.title.clone(),
                body: p.blurb.clone(),
                status: p.status.clone(),
                tags: p.tags.clone(),
                url: p.url.clone(),
            })
            .collect()
    }

    /// Snapshot the `comment` table into `app_notes::CommentRow`s.
    pub fn read_comments(conn: &bindings::DbConnection) -> Vec<app_notes::CommentRow> {
        conn.db
            .comment()
            .iter()
            .map(|c| app_notes::CommentRow {
                id: c.id,
                post_slug: c.post_slug.clone(),
                author_name: c.author_name.clone(),
                body: c.body.clone(),
                status: c.status.clone(),
            })
            .collect()
    }
}
