//! Thin wrapper over `spacetimedb-sdk` for the sastaspace TUI.
//!
//! Re-exports the auto-generated module bindings under `bindings::*` and
//! provides a `StdbHandle` that owns the connection and exposes typed
//! access to tables and reducers.
//!
//! Bindings live in `src/bindings/` (generated by `build_bindings.sh`
//! using `spacetime generate --lang rust --bin-path <wasm>`; checked in
//! per repo convention).

#![allow(clippy::all, dead_code)] // generated bindings are noisy

pub mod bindings;
pub mod connection;

pub use connection::{StdbConfig, StdbError, StdbHandle, StdbStatus};
