//! Thin wrapper over `spacetimedb-sdk` for the sastaspace TUI.
//!
//! Re-exports the auto-generated module bindings under `bindings::*` and
//! provides a `StdbHandle` that owns the connection and exposes typed
//! access to tables and reducers.
//!
//! Bindings live in `src/bindings/` (generated by `build_bindings.sh`
//! using `spacetime generate --lang rust --bin-path <wasm>`; checked in
//! per repo convention).

#![allow(clippy::all, dead_code)] // generated bindings are noisy

pub mod bindings;
pub mod bindings_typewars;
pub mod connection;

pub use connection::{StdbConfig, StdbError, StdbHandle, StdbStatus};

/// Helpers that read STDB tables and convert rows into shapes app crates use.
/// Kept as a thin module here so app crates don't need to know about
/// `spacetimedb-sdk` directly.
pub mod sub_helpers {
    use crate::bindings::{
        self, comment_table::CommentTableAccess, generate_job_table::GenerateJobTableAccess,
        plan_request_table::PlanRequestTableAccess, project_table::ProjectTableAccess,
    };
    use spacetimedb_sdk::Table;

    /// Snapshot the `project` table into `app_portfolio::ProjectRow`s.
    /// Called from the shell whenever an `Updated("project")` event arrives.
    pub fn read_projects(conn: &bindings::DbConnection) -> Vec<app_portfolio::ProjectRow> {
        conn.db
            .project()
            .iter()
            .map(|p| app_portfolio::ProjectRow {
                slug: p.slug.clone(),
                title: p.title.clone(),
                blurb: p.blurb.clone(),
                status: p.status.clone(),
            })
            .collect()
    }

    /// Snapshot the `project` table into `app_notes::NoteRow`s.
    /// All projects are treated as notes for v1 (no `kind` field in schema).
    pub fn read_notes(conn: &bindings::DbConnection) -> Vec<app_notes::NoteRow> {
        conn.db
            .project()
            .iter()
            .map(|p| app_notes::NoteRow {
                slug: p.slug.clone(),
                title: p.title.clone(),
                body: p.blurb.clone(),
                status: p.status.clone(),
                tags: p.tags.clone(),
                url: p.url.clone(),
            })
            .collect()
    }

    /// Snapshot the `comment` table into `app_notes::CommentRow`s.
    pub fn read_comments(conn: &bindings::DbConnection) -> Vec<app_notes::CommentRow> {
        conn.db
            .comment()
            .iter()
            .map(|c| app_notes::CommentRow {
                id: c.id,
                post_slug: c.post_slug.clone(),
                author_name: c.author_name.clone(),
                body: c.body.clone(),
                status: c.status.clone(),
            })
            .collect()
    }

    /// A minimal view of a `plan_request` row passed to the deck app.
    pub struct PlanRequestView {
        pub id: u64,
        pub status: String,
        pub tracks_json: Option<String>,
        pub error: Option<String>,
    }

    /// Snapshot the `plan_request` table (all rows visible to this identity).
    pub fn read_plan_requests(conn: &bindings::DbConnection) -> Vec<PlanRequestView> {
        conn.db
            .plan_request()
            .iter()
            .map(|r| PlanRequestView {
                id: r.id,
                status: r.status.clone(),
                tracks_json: r.tracks_json.clone(),
                error: r.error.clone(),
            })
            .collect()
    }

    /// A minimal view of a `generate_job` row passed to the deck app.
    pub struct GenerateJobView {
        pub id: u64,
        pub status: String,
        pub zip_url: Option<String>,
        pub error: Option<String>,
    }

    /// Snapshot the `generate_job` table (all rows visible to this identity).
    pub fn read_generate_jobs(conn: &bindings::DbConnection) -> Vec<GenerateJobView> {
        conn.db
            .generate_job()
            .iter()
            .map(|j| GenerateJobView {
                id: j.id,
                status: j.status.clone(),
                zip_url: j.zip_url.clone(),
                error: j.error.clone(),
            })
            .collect()
    }
}
