apiVersion: v1
kind: Secret
metadata:
  name: espocrm-env
  namespace: espocrm
type: Opaque
stringData:
  ESPOCRM_DATABASE_PASSWORD: "changeme-espocrm-db-password"
  MYSQL_ROOT_PASSWORD: "changeme-root-password"
  ESPOCRM_ADMIN_PASSWORD: "changeme-admin-password"
