{
 "title": "Pod Logs (Loki)",
 "tags": [
  "logs",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "query": "label_values({namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values({namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\"} [$__interval])) by (namespace)"
    }
   ]
  },
  {
   "title": "Pod Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |= \"$search\""
    }
   ]
  },
  {
   "title": "Error Logs (last 1h)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\"} |~ \"(?i)(error|exception|traceback|fatal|panic)\""
    }
   ]
  },
  {
   "title": "Worker Job Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{namespace=\"sastaspace\", pod=~\"worker.*\"} |= \"JOB\""
    }
   ]
  }
 ]
}